oro_chart:
    campaign_line_chart:
        label: oro.chart.line_chart.label
        data_schema:
            label:
                name: label
                label: orocrm.campaign.trackingevent.report.date.label
                required: true
                default_type: string
                field_name: logTime
            value:
                name: value
                label: orocrm.campaign.trackingevent.report.visits_count.label
                required: true
                default_type: integer
                field_name: visitsCount
        default_settings:
            connect_dots_with_line: true
            available_in_reports: false
            chartColors: ['#6598DA', '#ECC87E', '#A4A2F6', '#65BC87', '#8985C2', '#ECB574', '#84A377']
            chartFontSize: 9
            chartFontColor: '#454545'
            chartHighlightColor: '#FF5E5E'
            groupingOption: name
        data_transformer: orocrm_campaign.data_transformer.multi_line
        template: OroCRMCampaignBundle:Chart:multiline.html.twig
