oro_entity:
    virtual_relations:
        OroCRM\Bundle\CampaignBundle\Entity\Campaign:
            trackingEvent:
                relation_type: oneToMany
                related_entity_name: Oro\Bundle\TrackingBundle\Entity\TrackingEvent
                label: oro.tracking.trackingevent.entity_label
                query:
                    join:
                        left:
                            - { join: 'Oro\Bundle\TrackingBundle\Entity\TrackingEvent', alias: trackingEvent, conditionType: 'WITH', condition: 'trackingEvent.code = entity.code' }
