services:

    orocrm_contact.api.contact.customize_loaded_data.compute_primary_phone:
        class: Oro\Bundle\ApiBundle\Processor\CustomizeLoadedData\ComputePrimaryField
        arguments: [primaryPhone, phones, phone]
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, class: OroCRM\Bundle\ContactBundle\Entity\Contact }

    orocrm_contact.api.contact.customize_loaded_data.map_primary_phone:
        class: Oro\Bundle\ApiBundle\Processor\CustomizeFormData\MapPrimaryField
        arguments: ['@property_accessor', 'Unknown primary phone number.', primaryPhone, phones, phone]
        tags:
            - { name: oro.api.processor, action: customize_form_data, class: OroCRM\Bundle\ContactBundle\Entity\Contact }

    orocrm_contact.api.contact.customize_loaded_data.compute_primary_email:
        class: Oro\Bundle\ApiBundle\Processor\CustomizeLoadedData\ComputePrimaryField
        arguments: [primaryEmail, emails, email]
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, class: OroCRM\Bundle\ContactBundle\Entity\Contact }

    orocrm_contact.api.contact.customize_loaded_data.map_primary_email:
        class: Oro\Bundle\ApiBundle\Processor\CustomizeFormData\MapPrimaryField
        arguments: ['@property_accessor', 'Unknown primary email address.', primaryEmail, emails, email]
        tags:
            - { name: oro.api.processor, action: customize_form_data, class: OroCRM\Bundle\ContactBundle\Entity\Contact }
