parameters:
    oro_campaign.entity.class:                  Oro\Bundle\CampaignBundle\Entity\Campaign
    oro_campaign.tracking_event_summary.class:  Oro\Bundle\CampaignBundle\Entity\TrackingEventSummary
    oro_campaign.email_campaign_statistics.class: Oro\Bundle\CampaignBundle\Entity\EmailCampaignStatistics
    oro_campaign.email_campaign.entity.class:   Oro\Bundle\CampaignBundle\Entity\EmailCampaign
    oro_campaign.campaign.form.type.class:      Oro\Bundle\CampaignBundle\Form\Type\CampaignType
    oro_campaign.campaign.manager.api.class:    Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    oro_campaign.email_campaign.manager.api.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

    oro_campaign.data_transformer.multi_line.class: Oro\Bundle\CampaignBundle\Model\Data\Transformer\MultiLineDataTransformer
    oro_campaign.form.type.campaign_select.class: Oro\Bundle\CampaignBundle\Form\Type\CampaignSelectType
    oro_campaign.form.type.email_campaign.class: Oro\Bundle\CampaignBundle\Form\Type\EmailCampaignType
    oro_campaign.form.type.email_transport_select.class: Oro\Bundle\CampaignBundle\Form\Type\EmailTransportSelectType
    oro_campaign.transport.email.class: Oro\Bundle\CampaignBundle\Transport\EmailTransport
    oro_campaign.email_campaign.sender.class: Oro\Bundle\CampaignBundle\Model\EmailCampaignSender
    oro_campaign.email_transport.provider.class: Oro\Bundle\CampaignBundle\Provider\EmailTransportProvider
    oro_campaign.email_campaign.sender.builder.class: Oro\Bundle\CampaignBundle\Model\EmailCampaignSenderBuilder

    oro_campaign.listener.email_campaign_statistic_groupping.class: Oro\Bundle\CampaignBundle\EventListener\CampaignStatisticGroupingListener
    oro_campaign.listener.email_campaign_statistic.class: Oro\Bundle\CampaignBundle\EventListener\CampaignStatisticDatagridListener
    oro_campaign.listener.email_campaign_statistic_connector.cache_clear.class: Oro\Bundle\CampaignBundle\EventListener\EmailCampaignStatisticConnectorCacheClearListener
    oro_campaign.form.type.internal_transport_settings.class: Oro\Bundle\CampaignBundle\Form\Type\InternalTransportSettingsType
    oro_campaign.form.subscriber.transport_settings.class: Oro\Bundle\CampaignBundle\Form\EventListener\TransportSettingsListener
    oro_campaign.form.subscriber.transport_settings_email_template.class: Oro\Bundle\CampaignBundle\Form\EventListener\TransportSettingsEmailTemplateListener
    oro_campaign.form.handler.email_campaign.class: Oro\Bundle\CampaignBundle\Form\Handler\EmailCampaignHandler

    oro_campaign.email_campaign.statistics_connector.class: Oro\Bundle\CampaignBundle\Model\EmailCampaignStatisticsConnector

    oro_campaign.provider.tracking_identificator.class: Oro\Bundle\CampaignBundle\Provider\TrackingVisitEventIdentification
    oro_campaign.provider.privilege_category_provider.class: Oro\Bundle\CampaignBundle\Provider\PrivilegeCategoryProvider
services:
    oro_campaign.campaign.form.type:
        class: %oro_campaign.campaign.form.type.class%
        tags:
            - { name: form.type, alias: oro_campaign_form }

    oro_campaign.campaign.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "oro_campaign_form"
            - "oro_campaign_form"

    oro_campaign.email_campaign.form.type:
        class: %oro_campaign.form.type.email_campaign.class%
        calls:
            - [addSubscriber,  ["@oro_campaign.form.subscriber.transport_settings"]]
        tags:
            - { name: form.type, alias: oro_email_campaign }
        arguments:
            - "@oro_campaign.email_transport.provider"

    oro_campaign.email_campaign.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "oro_email_campaign"
            - "oro_email_campaign"

    oro_campaign.campaign.manager.api:
        class: %oro_campaign.campaign.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %oro_campaign.entity.class%
            - "@doctrine.orm.entity_manager"

    oro_campaign.email_campaign.manager.api:
        class: %oro_campaign.email_campaign.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %oro_campaign.email_campaign.entity.class%
            - "@doctrine.orm.entity_manager"

    oro_campaign.data_transformer.multi_line:
        class: %oro_campaign.data_transformer.multi_line.class%

    oro_campaign.form.autocomplete.campaign.search_handler:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - %oro_campaign.entity.class%
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: campaigns, acl_resource: oro_campaign_view }

    oro_campaign.form.type.campaign_select:
        class: %oro_campaign.form.type.campaign_select.class%
        tags:
            - { name: form.type, alias: "oro_campaign_select" }

    oro_campaign.form.type.email_transport_select:
        class: %oro_campaign.form.type.email_transport_select.class%
        arguments:
            - "@oro_campaign.email_transport.provider"
        tags:
            - { name: form.type, alias: "oro_campaign_email_transport_select" }

    oro_campaign.transport.email:
        class: %oro_campaign.transport.email.class%
        arguments:
            - "@oro_email.mailer.processor"
            - "@oro_email.email_renderer"
            - "@oro_entity.doctrine_helper"
            - "@oro_email.email.address.helper"
        tags:
            - { name: "oro_campaign.email_transport" }

    oro_campaign.email_campaign.statistics_connector:
        class: %oro_campaign.email_campaign.statistics_connector.class%
        arguments:
            - "@oro_marketing_list.model.marketing_list_item_connector"
            - "@oro_entity.doctrine_helper"
        calls:
            - [setEntityName, [%oro_campaign.email_campaign_statistics.class%]]

    oro_campaign.email_campaign.sender:
        class: %oro_campaign.email_campaign.sender.class%
        arguments:
            - "@oro_marketing_list.provider.marketing_list"
            - "@oro_config.user"
            - "@oro_campaign.email_campaign.statistics_connector"
            - "@oro_marketing_list.provider.contact_information_fields"
            - "@doctrine"
            - "@oro_campaign.email_transport.provider"
        calls:
            - [setLogger,  ["@logger"]]
            - [setValidator,  ["@validator"]]

    oro_campaign.email_transport.provider:
        class: %oro_campaign.email_transport.provider.class%

    oro_campaign.email_campaign.sender.builder:
        class: %oro_campaign.email_campaign.sender.builder.class%
        arguments:
            - "@oro_campaign.email_campaign.sender"

    oro_campaign.listener.email_campaign_statistic:
        class: %oro_campaign.listener.email_campaign_statistic.class%
        arguments:
            - "@oro_marketing_list.model.helper"
            - "@doctrine"
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.pre, method: onPreBuild, priority: 300 }

    oro_campaign.listener.email_campaign_statistic_groupping:
        class: %oro_campaign.listener.email_campaign_statistic_groupping.class%
        arguments:
            - "@oro_marketing_list.model.helper"
            - "@oro_campaign.group_by_helper"
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.pre, method: onPreBuild, priority: -10 }

    oro_campaign.listener.email_campaign_statistic_connector.cache_clear:
        class: %oro_campaign.listener.email_campaign_statistic_connector.cache_clear.class%
        arguments:
            - "@oro_campaign.email_campaign.statistics_connector"
        tags:
            - { name: doctrine.event_subscriber }

    oro_campaign.form.type.internal_transport_settings:
        class: %oro_campaign.form.type.internal_transport_settings.class%
        arguments:
            - "@doctrine"
        calls:
            - [addSubscriber,  ["@oro_campaign.form.subscriber.transport_settings_email_template"]]
        tags:
            - { name: form.type, alias: "oro_campaign_internal_transport_settings" }

    oro_campaign.form.subscriber.transport_settings:
        class: %oro_campaign.form.subscriber.transport_settings.class%
        arguments:
            - "@oro_campaign.email_transport.provider"
            - "@oro_entity.doctrine_helper"

    oro_campaign.form.subscriber.transport_settings_email_template:
        class: %oro_campaign.form.subscriber.transport_settings_email_template.class%
        arguments:
            - "@doctrine"
            - "@security.context"

    oro_campaign.form.handler.email_campaign:
        class: %oro_campaign.form.handler.email_campaign.class%
        scope: request
        arguments:
            - "@request"
            - "@oro_campaign.email_campaign.form"
            - "@doctrine"

    oro_campaign.group_by_helper:
        alias: oro_query_designer.group_by_helper

    oro_campaign.provider.tracking_identificator:
        class: %oro_campaign.provider.tracking_identificator.class%
        arguments:
           - "@doctrine"
        tags:
           - {name: oro_tracking.provider.identification, priority: 10}

    oro_campaign.provider.privilege_category_provider:
        class: %oro_campaign.provider.privilege_category_provider.class%
        tags:
            - { name: oro_user.privilege_category}

    oro_campaign.dashboard.campaign_data_provider:
        class: Oro\Bundle\CampaignBundle\Dashboard\CampaignDataProvider
        arguments:
            - '@doctrine'
            - '@oro_security.acl_helper'
            - '@oro_dashboard.filter.date_filter_processor'
