Oro\Bundle\MarketingListBundle\Entity\MarketingList:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ name ]
    properties:
        name:
            - NotBlank:     ~
            - Length:
                max: 255
        type:
            - NotBlank:     ~
        entity:
            - NotBlank:     ~
            - Length:
                max: 255
        organization:
            - NotBlank: ~
        segment:
            - Valid: ~

Oro\Bundle\SegmentBundle\Entity\Segment:
    constraints:
        - Oro\Bundle\MarketingListBundle\Validator\Constraints\ContactInformationColumnConstraint:
            groups: ["marketing_list"]

Oro\Bundle\MarketingListBundle\Entity\MarketingListItem:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ entityId, marketingList ]
    properties:
        entityId:
            - NotBlank: ~
            - Length:
                max: 255
        marketingList:
            - NotBlank:     ~


Oro\Bundle\MarketingListBundle\Entity\MarketingListItem:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ entityId, marketingList ]
    properties:
        entityId:
            - NotBlank: ~
            - Length:
                max: 255
        marketingList:
            - NotBlank:     ~


Oro\Bundle\MarketingListBundle\Entity\MarketingListRemovedItem:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ entityId, marketingList ]
    properties:
        entityId:
            - NotBlank: ~
            - Length:
                max: 255
        marketingList:
            - NotBlank:     ~



Oro\Bundle\MarketingListBundle\Entity\MarketingListUnsubscribedItem:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ entityId, marketingList ]
    properties:
        entityId:
            - NotBlank: ~
            - Length:
                max: 255
        marketingList:
            - NotBlank:     ~
