workflows:
    b2b_flow_lead:
        transitions:
            qualify:
                label: 'Qualify'
                step_to: qualified
                is_start: true
                is_unavailable_hidden: true
                acl_resource: orocrm_sales_opportunity_create
                frontend_options:
                    icon: 'icon-ok'
                    class: 'btn-primary'
                form_options:
                    attribute_fields:
                        opportunity_name:
                            form_type: text
                            options:
                                required: true
                                constraints:
                                  - NotBlank: ~
                        b2bcustomer:
                            form_type: orocrm_sales_b2bcustomer_select
                            options:
                                required: false
                                channel_id: $dataChannel.id
                        company_name:
                            form_type: text
                            options:
                                required: false
                        notes:
                            form_type: oro_resizeable_rich_text
                            options:
                                required: false
                    attribute_default_values:
                        opportunity_name: $lead.name
                        b2bcustomer: $lead.customer
                        company_name: $lead.companyName
                        notes: $lead.notes
                    init_actions:
                        - '@find_entity': # try to find customer by company name
                            conditions:
                                '@and': # if customer is empty and company name is specified
                                    - '@empty':     $b2bcustomer
                                    - '@not_empty': $company_name
                            parameters:
                                class:     OroCRM\Bundle\SalesBundle\Entity\B2bCustomer
                                attribute: $b2bcustomer
                                where:
                                    name: $company_name
                                case_insensitive: true
                transition_definition: qualify_definition
            cancel:
                label: 'Disqualify'
                step_to: cancelled
                is_start: true
                is_unavailable_hidden: true
                frontend_options:
                    icon: 'icon-remove'
                transition_definition: cancel_definition
            reactivate:
                label: 'Reactivate'
                step_to: new
                is_start: true
                is_unavailable_hidden: true
                frontend_options:
                    icon: 'icon-repeat'
                transition_definition: reactivate_definition
