elements:
  Account:
    selector: 'div#container'
    class: Oro\Bundle\TestFrameworkBundle\Behat\Element\Form
    options:
      mapping:
        Account Name: 'oro_account_form[name]'
        Description: 'oro_account_form[extend_description]'
