parameters:
    # entity
    oro_channel.entity.class:                                       Oro\Bundle\ChannelBundle\Entity\Channel

    # builder
    oro_channel.builder.factory.class:                              Oro\Bundle\ChannelBundle\Builder\BuilderFactory

    # handlers
    oro_channel.channel_form.handler.class:                         Oro\Bundle\ChannelBundle\Form\Handler\ChannelHandler
    oro_channel.channel_integration_form.handler.class:             Oro\Bundle\ChannelBundle\Form\Handler\ChannelIntegrationHandler

    # forms
    oro_channel.form.type.channel.class:                               Oro\Bundle\ChannelBundle\Form\Type\ChannelType
    oro_channel.form.type.entity.class:                                Oro\Bundle\ChannelBundle\Form\Type\ChannelEntityType
    oro_channel.form.type.channel_datasource.class:                    Oro\Bundle\ChannelBundle\Form\Type\ChannelDatasourceType
    oro_channel.form.type.channel_select.class:                        Oro\Bundle\ChannelBundle\Form\Type\ChannelSelectType
    oro_channel.form.type.create_or_select_inline_channel_aware.class: Oro\Bundle\ChannelBundle\Form\Type\CreateOrSelectInlineChannelAwareType
    oro_channel.form.type.multiple_entity_channel_aware.class:         Oro\Bundle\ChannelBundle\Form\Type\MultipleEntityChannelAwareType
    oro_channel.form.embedded_type_extension.class:                    Oro\Bundle\ChannelBundle\Form\Extension\EmbeddedFormTypeExtension
    oro_channel.form.integration_type_extension.class:                 Oro\Bundle\ChannelBundle\Form\Extension\IntegrationTypeExtension

    # manager
    oro_channel.manager.channel.api.class:                             Oro\Bundle\ChannelBundle\Entity\Manager\ChannelApiEntityManager
    oro_channel.manager.customer_search.api.class:                     Oro\Bundle\ChannelBundle\Entity\Manager\CustomerSearchApiEntityManager

    # providers
    oro_channel.provider.settings_provider.class:                   Oro\Bundle\ChannelBundle\Provider\SettingsProvider
    oro_channel.provider.exclusion_provider.class:                  Oro\Bundle\ChannelBundle\Provider\EntityExclusionProvider
    oro_channel.provider.channel_entity_exclusion_provider.class:   Oro\Bundle\ChannelBundle\Provider\ChannelEntityExclusionProvider
    oro_channel.provider.state_provider.class:                      Oro\Bundle\ChannelBundle\Provider\StateProvider
    oro_channel.provider.entity_metadata.class:                     Oro\Bundle\ChannelBundle\Provider\MetadataProvider
    oro_channel.provider.utils.entity_state_provider.class:         Oro\Bundle\ChannelBundle\Provider\Utility\EntityStateProvider
    oro_channel.provider.request_channel.class:                     Oro\Bundle\ChannelBundle\Provider\RequestChannelProvider
    oro_channel.provider.lifetime.amount_provider.class:            Oro\Bundle\ChannelBundle\Provider\Lifetime\AmountProvider
    oro_channel.provider.lifetime.average_widget_provider.class:    Oro\Bundle\ChannelBundle\Provider\Lifetime\AverageLifetimeWidgetProvider

    # datagrid
    oro_channel.datagrid.extension.orm_channel_limitation.class:    Oro\Bundle\ChannelBundle\Datagrid\ChannelLimitationExtension

    # autocomplete
    oro_channel.autocomplete.channel_limitation_handler.class:      Oro\Bundle\ChannelBundle\Autocomplete\ChannelLimitationHandler

    # config resolver
    oro_channel.config_resolver.class:                              Oro\Component\Config\Resolver\SystemAwareResolver

    # event listener
    oro_channel.event_listener.navigation.class:                    Oro\Bundle\ChannelBundle\EventListener\NavigationListener
    oro_channel.form.subscriber.channel_subscriber.class:           Oro\Bundle\ChannelBundle\Form\EventListener\ChannelTypeSubscriber
    oro_channel.event_listener.update_integration_connectors.class: Oro\Bundle\ChannelBundle\EventListener\UpdateIntegrationConnectorsListener
    oro_channel.event_listener.channel_before_deleted.class:        Oro\Bundle\ChannelBundle\EventListener\ChannelBeforeDeleteListener
    oro_channel.event_listener.embedded_form.class:                 Oro\Bundle\ChannelBundle\EventListener\EmbeddedFormListener
    oro_channel.event_listener.doctrine.class:                      Oro\Bundle\ChannelBundle\EventListener\ChannelDoctrineListener
    oro_channel.event_listener.timezone_change.class:               Oro\Bundle\ChannelBundle\EventListener\TimezoneChangeListener
    oro_channel.event_listener.job_execution.class:                 Oro\Bundle\ChannelBundle\EventListener\JobExecutionSubscriber
    oro_channel.event_listener.transitions_attribute.class:         Oro\Bundle\ChannelBundle\EventListener\TransitionsAttributeListener

    #validators
    oro_channel.validators.channel_integration_validator.class:     Oro\Bundle\ChannelBundle\Validator\ChannelIntegrationConstraintValidator

    # import/export
    oro_channel.importexport.helper.channel.class:                  Oro\Bundle\ChannelBundle\ImportExport\Helper\ChannelHelper

services:
    oro_channel.builder.factory:
        class: %oro_channel.builder.factory.class%
        arguments:
          - "@doctrine"
          - "@oro_channel.provider.settings_provider"

    # forms
    oro_channel.form.type.channel:
        class: %oro_channel.form.type.channel.class%
        arguments:
            - "@oro_channel.provider.settings_provider"
            - "@oro_channel.form.subscriber.channel_subscriber"
        tags:
            - { name: form.type, alias: oro_channel_form }

    oro_channel.form.type.entity:
        class: %oro_channel.form.type.entity.class%
        tags:
            - { name: form.type, alias: oro_channel_entities }

    oro_channel.form.type.channel_datasource:
        class: %oro_channel.form.type.channel_datasource.class%
        arguments:
            - "@doctrine"
            - %oro_integration.entity.class%
        tags:
            - { name: form.type, alias: oro_channel_datasource_form }

    oro_channel.form.type.channel_select:
        class: %oro_channel.form.type.channel_select.class%
        arguments:
            - '@oro_channel.provider.channels_by_entities'
        tags:
            - { name: form.type, alias: oro_channel_select_type }

    oro_channel.form.type.create_or_select_inline_channel_aware:
        class: %oro_channel.form.type.create_or_select_inline_channel_aware.class%
        tags:
            - { name: form.type, alias: oro_entity_create_or_select_inline_channel_aware }

    oro_channel.form.type.multiple_entity_channel_aware:
        class: %oro_channel.form.type.multiple_entity_channel_aware.class%
        tags:
            - { name: form.type, alias: oro_multiple_entity_channel_aware }

    oro_channel.form.channel:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', 'createNamed']
        arguments: ["oro_channel_form", "oro_channel_form", null]

    # handlers
    oro_channel.channel_form.handler:
        class: %oro_channel.channel_form.handler.class%
        scope: request
        arguments:
            - "@request"
            - "@oro_channel.form.channel"
            - "@doctrine"
            - "@event_dispatcher"

    oro_channel.channel_integration_form.handler:
        class: %oro_channel.channel_integration_form.handler.class%
        scope: request
        arguments:
            - "@request"
            - "@form.factory"

    # Channel API
    oro_channel.manager.channel.api:
        class: %oro_channel.manager.channel.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %oro_channel.entity.class%
            - "@doctrine.orm.entity_manager"

    oro_channel.manager.customer_search.api:
        class: %oro_channel.manager.customer_search.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %oro_channel.entity.class%
            - "@doctrine.orm.entity_manager"
            - "@oro_search.index"
            - "@event_dispatcher"
            - "@oro_channel.provider.settings_provider"

    # Providers
    oro_channel.provider.settings_provider:
        class: %oro_channel.provider.settings_provider.class%
        arguments:
            - []
            - "@oro_channel.config_resolver"

    oro_channel.provider.exclusion_provider:
        class: %oro_channel.provider.exclusion_provider.class%
        arguments:
            - "@oro_channel.provider.settings_provider"
            - "@oro_channel.provider.state_provider"
        tags:
            - { name: oro_entity.exclusion_provider.default }

    oro_channel.provider.metadata_provider:
        class: %oro_channel.provider.entity_metadata.class%
        arguments:
            - "@oro_channel.provider.settings_provider"
            - "@oro_entity.entity_provider"
            - "@oro_entity_config.config_manager"
            - "@router"

    oro_channel.provider.request_channel:
        class: %oro_channel.provider.request_channel.class%
        arguments:
            - "@request"
            - "@doctrine"
        scope: request

    # datagrid
    oro_channel.datagrid.extension.orm_channel_limitation:
        class: %oro_channel.datagrid.extension.orm_channel_limitation.class%
        tags:
            - { name: oro_datagrid.extension }

    # autocomplete
    oro_channel.autocomplete.channel_limitation_handler:
        class: %oro_channel.autocomplete.channel_limitation_handler.class%
        calls:
            - [initDoctrinePropertiesByManagerRegistry, ["@doctrine"]]
            - [initSearchIndexer, ["@oro_search.index", %oro_search.entities_config%]]
            - [setAclHelper,["@oro_security.acl_helper"]]

    # config resolver
    oro_channel.provider.channel_entity_exclusion_provider:
        class: %oro_channel.provider.channel_entity_exclusion_provider.class%
        arguments:
            - "@oro_channel.provider.settings_provider"

    oro_channel.provider.channel_entity_provider:
        class: %oro_entity.entity_provider.class%
        parent: oro_entity.entity_provider.abstract
        calls:
            - [setExclusionProvider,  ["@oro_channel.provider.channel_entity_exclusion_provider"]]

    oro_channel.provider.state_provider:
        class: %oro_channel.provider.state_provider.class%
        arguments:
            - "@oro_channel.provider.settings_provider"
            - "@oro_channel.state_cache"
            - "@doctrine"
            - "@oro_security.token_accessor"
            - "@oro_security.acl_helper"

    oro_channel.provider.utils.entity_state_provider:
        class: %oro_channel.provider.utils.entity_state_provider.class%
        abstract: true
        calls:
            - [setStateProvider,  ["@oro_channel.provider.state_provider"]]

    oro_channel.provider.lifetime.amount_provider:
        class: %oro_channel.provider.lifetime.amount_provider.class%
        arguments:
            - "@doctrine"

    oro_channel.provider.lifetime.average_widget_provider:
        class: %oro_channel.provider.lifetime.average_widget_provider.class%
        arguments:
            - '@doctrine'
            - '@oro_locale.settings'
            - '@oro_security.acl_helper'
            - '@oro_dashboard.filter.date_filter_processor'

    oro_channel.config_resolver:
        class: %oro_channel.config_resolver.class%
        arguments:
            - "@service_container"

    # event listeners
    oro_channel.event_listener.navigation:
        class: %oro_channel.event_listener.navigation.class%
        arguments:
            - "@oro_channel.provider.settings_provider"
            - "@oro_channel.provider.state_provider"
        tags:
            - { name: kernel.event_listener, event: oro_menu.configure.application_menu, method: onNavigationConfigure }
            - { name: kernel.event_listener, event: oro_menu.configure.shortcuts, method: onNavigationConfigure }

    oro_channel.state_cache:
          parent: oro.cache.abstract
          calls:
              - [setNamespace, [ 'oro_channel_state' ] ]

    oro_channel.form.subscriber.channel_subscriber:
        class: %oro_channel.form.subscriber.channel_subscriber.class%
        arguments:
            - "@oro_channel.provider.settings_provider"

    oro_channel.event_listener.update_integration_connectors:
        class: %oro_channel.event_listener.update_integration_connectors.class%
        arguments:
            - "@oro_channel.provider.settings_provider"
            - "@doctrine"
        tags:
            - { name: kernel.event_listener, event: oro_channel.channel.save_succeed, method: onChannelSave }

    oro_channel.event_listener.channel_succeed_deleted:
        class: %oro_channel.event_listener.channel_before_deleted.class%
        arguments:
            - "@oro_integration.delete_manager"
        tags:
            - { name: kernel.event_listener, event: oro_channel.channel.before_delete, method: onChannelBeforeDelete }

    oro_channel.event_listener.embedded_form:
        class: %oro_channel.event_listener.embedded_form.class%
        calls:
            - [setRequest, ['@?request=']]
        tags:
            - { name: kernel.event_listener, event: entity_form.render.before, method: addDataChannelField }
            - { name: kernel.event_listener, event: oro_embedded_form.form_submit.before, method: onEmbeddedFormSubmit }

    oro_channel.event_listener.doctrine:
      class: %oro_channel.event_listener.doctrine.class%
      arguments:
          - "@oro_channel.provider.settings_provider"
      tags:
        - { name: doctrine.event_listener, event: onFlush, method: onFlush }
        - { name: doctrine.event_listener, event: postFlush, method: postFlush }

    oro_channel.event_listener.refresh_channel_cache_listener:
          class: Oro\Bundle\ChannelBundle\EventListener\ORM\RefreshChannelCacheListener
          arguments:
              - '@oro_channel.provider.state_provider'
          tags:
            - { name: doctrine.orm.entity_listener, entity: '%oro_channel.entity.class%', event: prePersist }
            - { name: doctrine.orm.entity_listener, entity: '%oro_channel.entity.class%', event: postRemove }

    oro_channel.event_listener.timezone_change:
      class: 'Oro\Bundle\ChannelBundle\EventListener\TimezoneChangeListener'
      arguments:
          - "@oro_message_queue.message_producer"
      tags:
        - { name: kernel.event_listener, event: oro_config.update_after, method: onConfigUpdate }

    oro_channel.event_listener.job_execution:
        class: %oro_channel.event_listener.job_execution.class%
        arguments:
            - "@oro_entity.doctrine_helper"
            - "@security.token_storage"
        tags:
            - { name: kernel.event_subscriber }

    #twig
    oro_channel.twig.metadata_extension:
        class: Oro\Bundle\ChannelBundle\Twig\MetadataExtension
        public: false
        arguments:
            - "@service_container"
        tags:
            - { name: twig.extension }

    oro_channel.form.integration_type_extension:
        class: %oro_channel.form.integration_type_extension.class%
        arguments:
            - "@oro_channel.provider.settings_provider"
        tags:
            - { name: form.type_extension, alias: oro_integration_channel_form }

    oro_channel.form.embedded_type_extension:
        class: %oro_channel.form.embedded_type_extension.class%
        tags:
            - { name: form.type_extension, alias: embedded_form }

    oro_channel.twig.lifetime_value_extension:
        class: Oro\Bundle\ChannelBundle\Twig\LifetimeValueExtension
        public: false
        arguments:
            - '@service_container'
        tags:
            - { name: twig.extension }

    #validators
    oro_channel.validators.channel_integration_validator:
        class: %oro_channel.validators.channel_integration_validator.class%
        arguments:
            - "@oro_channel.provider.settings_provider"
        tags:
            - { name: validator.constraint_validator, alias: oro_channel.validator.channel_integration }

    # import/export
    oro_channel.importexport.helper.channel:
        class: %oro_channel.importexport.helper.channel.class%
        arguments:
            - "@doctrine"

    # conditions
    oro_workflow.condition.custom:
        class: 'Oro\Bundle\ChannelBundle\Model\Condition\ChannelEntityAvailability'
        arguments:
            - "@oro_channel.provider.state_provider"
        tags:
            - { name: oro_action.condition, alias: channel_entity_availiable }

    oro_channel.provider.channels_by_entities:
        class: Oro\Bundle\ChannelBundle\Provider\ChannelsByEntitiesProvider
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_security.acl_helper'

    oro_channel.form.extension.single_channel_mode:
        class: Oro\Bundle\ChannelBundle\Form\Extension\SingleChannelModeExtension
        arguments:
            - '@oro_channel.provider.channels_by_entities'
        tags:
            - { name: form.type_extension, alias: oro_channel_select_type }

    oro_channel.event_listener.transitions_attribute:
        class: %oro_channel.event_listener.transitions_attribute.class%
        arguments:
            - '@form.factory'
            - '@oro_action.expression.context_accessor'
        tags:
            - { name: kernel.event_listener, event: oro_workflow.transitions.attribute.before_add, method: beforeAddAttribute }

    oro_channel.async.change_integration_status_processor:
        class: 'Oro\Bundle\ChannelBundle\Async\ChangeIntegrationStatusProcessor'
        arguments:
            - '@doctrine'
            - '@logger'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_channel.async.process_channel_state_processor:
        class: 'Oro\Bundle\ChannelBundle\Async\ProcessChannelStateProcessor'
        arguments: ["@oro_channel.provider.state_provider"]
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_channel.async.aggregate_lifetime_average_processor:
        class: 'Oro\Bundle\ChannelBundle\Async\AggregateLifetimeAverageProcessor'
        arguments:
            - '@doctrine'
            - '@oro_locale.settings'
            - '@oro_message_queue.job.runner'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_channel.security.acl.voter.channel:
        class: 'Oro\Bundle\ChannelBundle\Acl\Voter\ChannelVoter'
        arguments:
            - "@oro_entity.doctrine_helper"
        calls:
            - [setClassName, ['Oro\Bundle\ChannelBundle\Entity\Channel']]
            - [setSettingsProvider,  ['@oro_channel.provider.settings_provider']]
        tags:
            - { name: security.voter, priority: 500 }

    oro_channel.account_lifetime_subscriber:
        class: Oro\Bundle\ChannelBundle\EventListener\AccountLifetimeSubscriber
        arguments:
            - '@service_container'
        tags:
            - { name: doctrine.event_subscriber }
