parameters:
    orocrm_account.importexport.template_fixture.account.class: OroCRM\Bundle\AccountBundle\ImportExport\TemplateFixture\AccountFixture
    orocrm_account.importexport.strategy.account.add_or_replace.class: OroCRM\Bundle\AccountBundle\ImportExport\Strategy\AccountAddOrReplaceStrategy

services:
    orocrm_account.importexport.data_converter:
        parent: oro_importexport.data_converter.configurable

    orocrm_account.importexport.template_fixture.data_converter.account:
        parent: oro_importexport.data_converter.template_fixture.configurable

    # Strategy
    orocrm_account.importexport.strategy.account.add_or_replace:
        class: %orocrm_account.importexport.strategy.account.add_or_replace.class%
        parent: oro_importexport.strategy.configurable_add_or_replace

    # Import processor
    orocrm_account.importexport.processor.import:
        parent: oro_importexport.processor.import_abstract
        calls:
             - [setDataConverter, ["@orocrm_account.importexport.data_converter"]]
             - [setStrategy, ["@orocrm_account.importexport.strategy.account.add_or_replace"]]
        tags:
            - { name: oro_importexport.processor, type: import, entity: %orocrm_account.account.entity.class%, alias: orocrm_account.add_or_replace }
            - { name: oro_importexport.processor, type: import_validation, entity: %orocrm_account.account.entity.class%, alias: orocrm_account.add_or_replace }

    # Export processor
    orocrm_account.importexport.processor.export:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, ["@orocrm_account.importexport.data_converter"]]
        tags:
            - { name: oro_importexport.processor, type: export, entity: %orocrm_account.account.entity.class%, alias: orocrm_account }

    orocrm_account.importexport.processor.export_template:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, ["@orocrm_account.importexport.template_fixture.data_converter.account"]]
        tags:
            - { name: oro_importexport.processor, type: export_template, entity: %orocrm_account.account.entity.class%, alias: orocrm_account }

    orocrm_account.importexport.template_fixture.account:
        class: %orocrm_account.importexport.template_fixture.account.class%
        tags:
            - { name: oro_importexport.template_fixture }
