OroCRM\Bundle\AccountBundle\Entity\Account:
    alias: orocrm_account
    label: Accounts
    title_fields: [name]
    route:
        name: orocrm_account_view
        parameters:
            id: id
    search_template: OroCRMAccountBundle:Account:searchResult.html.twig
    entity_icon_class: icon-home
    fields:
        -
            name: name
            target_type: text
            target_fields: [name]
