navigation:
    menu_config:
        items:
            marketing_lists_list:
                label: 'oro.marketinglist.entity_plural_label'
                route: 'oro_marketing_list_index'
                extras:
                    routes: ['oro_marketing_list_*']
                    position: 10
        tree:
            application_menu:
                children:
                    marketing_tab:
                        children:
                            marketing_lists_list: ~

    titles:
        oro_marketing_list_index:  ~
        oro_marketing_list_update: '%%entityName%% - Edit'
        oro_marketing_list_view: '%%entityName%%'
        oro_marketing_list_create: oro.ui.create_entity

    navigation_elements:
        pinButton:
            routes:
                oro_marketing_list_create: false
                oro_marketing_list_update: false
