datagrids:
    oro_reportcrm-accounts-life_time_value:
        pageTitle: oro.reportcrm.accounts_life_time_value
        acl_resource: oro_report_view
        source:
            type: orm
            query:
                select:
                    - a.id
                    - a.name
                    - SUM( CASE WHEN ch.status = true THEN lifetimeHistory.amount ELSE 0 END ) as value
                from:
                    - { table: OroAccountBundle:Account, alias: a }
                join:
                    left:
                        - { join: OroChannelBundle:LifetimeValueHistory, alias: lifetimeHistory, conditionType: WITH, condition: "lifetimeHistory.account = a and lifetimeHistory.status = true" }
                        - { join: lifetimeHistory.dataChannel, alias: ch  }
                groupBy:  a.id
        columns:
            name:   { label: oro.reportcrm.datagrid.columns.account_name }
            value:  { label: oro.account.lifetime_value.label,  frontend_type: currency }
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_account_view
                params:     [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  oro_account_view
                label:         oro.grid.action.view
                icon:          eye
                link:          view_link
                rowAction:     true
        totals:
            total:
                extends: grand_total
                per_page: true
                hide_if_one_page: true
                columns:
                    name:
                        label: oro.magento.datagrid.columns.page_total

            grand_total:
                columns:
                    name:
                        label: oro.magento.datagrid.columns.grand_total
                    value:
                        expr: SUM( CASE WHEN ch.status = true THEN lifetimeHistory.amount ELSE 0 END )
                        formatter: currency
        sorters:
            columns:
                name:   { data_name: a.name }
                value:  { data_name: value }
        filters:
            columns:
                name:
                    type: string
                    data_name: a.name
                value:
                    type:             currency
                    data_name:        value
                    filter_by_having: true
                    options:
                        data_type:    Oro\Bundle\FilterBundle\Form\Type\Filter\NumberFilterType::DATA_DECIMAL
        options:
            entityHint: report data
            export: true
            entity_pagination: true

    oro_reportcrm-accounts-by_opportunities:
        pageTitle: oro.reportcrm.accounts_by_opportunities
        acl_resource: oro_report_view
        source:
            type: orm
            query:
                from:
                    - { table: OroSalesBundle:Opportunity, alias: o }
                select:
                    - a.id
                    - a.name
                join:
                    inner:
                        - { join: o.customer, alias: c }
                        - { join: c.account, alias: a }
                        - { join: o.status, alias: s }
                groupBy:  a.id
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_account_view
                params:     [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  oro_account_view
                label:         oro.grid.action.view
                icon:          eye
                link:          view_link
                rowAction:     true
        totals:
            total:
                extends: grand_total
                per_page: true
                hide_if_one_page: true
                columns:
                    name:
                        label: oro.magento.datagrid.columns.page_total
            grand_total:
                columns:
                    name:
                        label: oro.magento.datagrid.columns.grand_total
        columns:
            name:             { label: oro.reportcrm.datagrid.columns.account_name }
        sorters:
            columns:
                name:              { data_name: a.name }
        filters:
            columns:
                name:
                    type:        string
                    data_name:   a.name
                closeDate:
                    type:        date
                    label:       oro.reportcrm.datagrid.columns.close_date
                    data_name:   o.closeDate
                createdAt:
                    type:        date
                    label:       oro.reportcrm.datagrid.columns.created_date
                    data_name:   o.createdAt
        options:
            entityHint: report data
            export: true
            entity_pagination: true

    oro_reportcrm-leads-by_date:
        pageTitle: oro.reportcrm.leads_by_date
        acl_resource: oro_report_view
        source:
            type: orm
            query:
                select:
                    - COUNT(l.id) as leadsCount
                    - DATE(l.createdAt) as createdDate
                from:
                    - { table: OroSalesBundle:Lead, alias: l }
                groupBy: createdDate
        totals:
            total:
                extends: grand_total
                per_page: true
                hide_if_one_page: true
                columns:
                    createdDate:
                        label: oro.magento.datagrid.columns.page_total
            grand_total:
                columns:
                    createdDate:
                        label: oro.magento.datagrid.columns.grand_total
                    leadsCount:
                        expr: COUNT(l.id)
        columns:
            createdDate:    { label: oro.reportcrm.datagrid.columns.created_date, frontend_type: date }
            leadsCount:     { label: oro.reportcrm.datagrid.columns.leads_count,  frontend_type: integer }
        sorters:
            columns:
                createdDate:   { data_name: createdDate }
                leadsCount:    { data_name: leadsCount }
        filters:
            columns:
                createdDate:   { type: date, data_name: createdDate, filter_by_having: true }
                leadsCount:    { type: number-range, data_name: leadsCount, filter_by_having: true }
        options:
            entityHint: report data
            export: true
            entity_pagination: true

    oro_reportcrm-opportunities-by_status:
        pageTitle: oro.reportcrm.opportunities_by_status
        acl_resource: oro_report_view
        source:
            type: orm
            query:
                #from: generated by OpportunitiesByStatusReportListener
                join:
                    # if any date filter is used, this will be replaced by OpportunitiesByStatusReportListener
                    left:
                        - { join: OroSalesBundle:Opportunity, alias: opportunity, conditionType: WITH, condition: "opportunity.status = status" }
                select:
                    - status.name as statusLabel
                    - status.priority as statusPriority
                    - COUNT(opportunity.id) as numberOfOpportunities
                    - >
                      SUM(
                        CASE WHEN status.id IN ('won', 'lost') THEN COALESCE(opportunity.closeRevenueValue, 0) ELSE 0 END
                      ) as closeRevenue
                    - SUM(COALESCE(opportunity.budgetAmountValue, 0)) as budgetAmount
                groupBy: statusLabel
        totals:
            total:
                extends: grand_total
                per_page: true
                hide_if_one_page: true
                columns:
                    statusLabel:
                        label: oro.magento.datagrid.columns.page_total
            grand_total:
                columns:
                    statusLabel:
                        label: oro.magento.datagrid.columns.grand_total
                    numberOfOpportunities:
                        expr: COUNT(opportunity.id)
                    closeRevenue:
                        expr: SUM(CASE WHEN status.id IN ('won', 'lost') THEN opportunity.closeRevenueValue ELSE 0 END)
                        formatter: currency
                    budgetAmount:
                        expr: SUM(COALESCE(opportunity.budgetAmountValue, 0))
                        formatter: currency
        columns:
            statusPriority:        { label: statusPriority, renderable: false, manageable: false }
            statusLabel:           { label: oro.reportcrm.datagrid.columns.status }
            numberOfOpportunities: { label: oro.reportcrm.datagrid.columns.number_of_opportunities, frontend_type: integer }
            closeRevenue:          { label: oro.reportcrm.datagrid.columns.close_revenue, frontend_type: currency }
            budgetAmount:          { label: oro.reportcrm.datagrid.columns.budget_amount, frontend_type: currency }
        sorters:
            columns:
                statusLabel:           { data_name: statusLabel }
                statusPriority:        { data_name: statusPriority }
                numberOfOpportunities: { data_name: numberOfOpportunities }
                closeRevenue:          { data_name: closeRevenue }
                budgetAmount:          { data_name: budgetAmount }
            default:
                statusPriority: ASC

        filters:
            columns:
                statusLabel:
                    type: enum
                    data_name: status.id
                    enum_code: opportunity_status
                numberOfOpportunities:
                    type: number-range
                    data_name: numberOfOpportunities
                    filter_by_having: true
                closeRevenue:
                    type: currency
                    data_name: closeRevenue
                    filter_by_having: true
                    options:
                        data_type: Oro\Bundle\FilterBundle\Form\Type\Filter\NumberFilterType::DATA_DECIMAL
                budgetAmount:
                    type: currency
                    data_name: budgetAmount
                    filter_by_having: true
                    options:
                        data_type: Oro\Bundle\FilterBundle\Form\Type\Filter\NumberFilterType::DATA_DECIMAL
                closeDate:
                    label:     oro.sales.opportunity.close_date.label
                    type:      date
                    data_name: opportunity.closeDate
                createdAt:
                    label:     oro.sales.opportunity.created_at.label
                    type:      datetime
                    data_name: opportunity.createdAt
                updatedAt:
                    label:     oro.sales.opportunity.updated_at.label
                    type:      datetime
                    data_name: opportunity.updatedAt

        options:
            entityHint: report data
            export: true
            entity_pagination: true

    oro_reportcrm-opportunities-won_by_period:
        pageTitle: oro.reportcrm.opportunities_won_by_period
        acl_resource: oro_report_view
        source:
            type: orm
            query:
                select:
                    - CONCAT(MONTH(o.closeDate), ' / ', YEAR(o.closeDate)) as monthPeriod
                    - MAX(o.closeDate) as monthPeriodSorting

                    - CONCAT(QUARTER(o.closeDate), ' / ', YEAR(o.closeDate)) as quarterPeriod
                    - MAX(o.closeDate) as quarterPeriodSorting

                    - YEAR(o.closeDate) as yearPeriod
                    - SUM(o.closeRevenueValue) as value
                    - COUNT(o.id) as cnt
                from:
                    - { table: OroSalesBundle:Opportunity, alias: o }
                join:
                    inner:
                        - { join: o.status, alias: s }
                groupBy: o.closeDate # will be overridden in ReportGridListener with selected period name (monthly or quarterly or yearly)
                where:
                    and:
                        - s.id = 'won'
                        - o.closeDate IS NOT NULL
        properties:
            monthPeriod: ~
            quarterPeriod: ~
            yearPeriod: ~
        totals:
            total:
                extends: grand_total
                per_page: true
                hide_if_one_page: true
                columns:
                    period:
                        label: oro.magento.datagrid.columns.page_total
            grand_total:
                columns:
                    period:
                        label: oro.magento.datagrid.columns.grand_total
                    cnt:
                        expr: COUNT( o.id )
                    value:
                        expr: SUM( o.closeRevenueValue )
                        formatter: currency

        columns:
            period:    { label: oro.reportcrm.datagrid.columns.period }
            cnt:       { label: oro.reportcrm.datagrid.columns.number_won, frontend_type: integer }
            value:     { label: oro.reportcrm.datagrid.columns.total_value, frontend_type: currency }
        sorters:
            columns:
                period:     { data_name: o.closeDate }
                cnt:        { data_name: cnt }
                value:      { data_name: value }
        filters:
            columns:
                period:
                    type: oro_period_filter
                    data_name: period
                    options:
                        populate_default: false
                        field_options:
                            choices:
                                monthPeriod:    Monthly
                                quarterPeriod:  Quarterly
                                yearPeriod:     Yearly
                cnt:
                    type: number-range
                    data_name: cnt
                    filter_by_having: true
                value:
                    type: currency
                    data_name: value
                    filter_by_having: true
                    options:
                        data_type:    Oro\Bundle\FilterBundle\Form\Type\Filter\NumberFilterType::DATA_DECIMAL
                closeDate:
                    type:        date
                    label:       oro.reportcrm.datagrid.columns.close_date
                    data_name:   o.closeDate
                createdAt:
                    type:        date
                    label:       oro.reportcrm.datagrid.columns.created_date
                    data_name:   o.createdAt
            default:
                period: { value: monthPeriod }
        options:
            entityHint: report data
            export: true
            entity_pagination: true

    oro_reportcrm-opportunities-total_forecast:
        pageTitle: oro.reportcrm.opportunities.total_forecast
        acl_resource: oro_report_view
        source:
            type: orm
            query:
                select:
                    - CONCAT(oo.firstName, CONCAT(' ', oo.lastName)) as ownerName
                    - SUM( (CASE WHEN (s.id NOT IN ('lost', 'won')) THEN 1 ELSE 0 END) ) as inProgressCount
                    - SUM( o.budgetAmountValue ) as budgetAmount
                    - SUM( o.budgetAmountValue * o.probability ) as weightedForecast
                from:
                    - { table: OroSalesBundle:Opportunity, alias: o }
                join:
                    inner:
                        - { join: o.status, alias: s }
                        - { join: o.owner, alias: oo }
                where:
                    and:
                        - o.probability <> 0
                        - o.probability <> 1
                    or:
                        - o.probability is NULL
                groupBy: oo.id
        totals:
            total:
                extends: grand_total
                per_page: true
                hide_if_one_page: true
                columns:
                    ownerName:
                        label: oro.magento.datagrid.columns.page_total
            grand_total:
                columns:
                    ownerName:
                        label: oro.magento.datagrid.columns.grand_total
                    inProgressCount:
                        expr: SUM( (CASE WHEN (s.id NOT IN ('lost', 'won')) THEN 1 ELSE 0 END) )
                    budgetAmount:
                        expr: SUM( o.budgetAmountValue )
                        formatter: currency
                    weightedForecast:
                        expr: SUM( o.budgetAmountValue * o.probability )
                        formatter: currency
        columns:
            ownerName:        { label: oro.reportcrm.datagrid.columns.ownerName,        frontend_type: string }
            inProgressCount:  { label: oro.reportcrm.datagrid.columns.inProgressCount,  frontend_type: integer }
            budgetAmount:     { label: oro.reportcrm.datagrid.columns.budgetAmount,     frontend_type: currency }
            weightedForecast: { label: oro.report.datagrid.columns.weightedForecast, frontend_type: currency }
        sorters:
            columns:
                ownerName:        { data_name: ownerName }
                inProgressCount:  { data_name: inProgressCount }
                budgetAmount:     { data_name: budgetAmount }
                weightedForecast: { data_name: weightedForecast }
        filters:
            columns:
                ownerName:
                    type: choice-tree
                    data_name: o.owner
                    autocomplete_alias: users
                    renderedPropertyName: 'fullName'
                    className: 'Oro\Bundle\UserBundle\Entity\User'
                inProgressCount:
                    type:      number-range
                    data_name: inProgressCount
                    filter_by_having: true
                    options:
                        data_type: Oro\Bundle\FilterBundle\Form\Type\Filter\NumberFilterType::DATA_INTEGER
                budgetAmount:
                    type:      currency
                    data_name: budgetAmount
                    filter_by_having: true
                    options:
                        data_type: Oro\Bundle\FilterBundle\Form\Type\Filter\NumberFilterType::DATA_DECIMAL
                weightedForecast:
                    type:      currency
                    data_name: weightedForecast
                    filter_by_having: true
                    options:
                        data_type: Oro\Bundle\FilterBundle\Form\Type\Filter\NumberFilterType::DATA_DECIMAL
        options:
            entityHint: report data
            export: true
        entity_pagination: true
