placeholders:
    page_header_stats_after:
        items:
            orocrm_activity_contact:
                order: 10

items:
    orocrm_activity_contact:
        template: OroCRMActivityContactBundle:ActivityContact:metrics.html.twig
        applicable: "@orocrm_activity_contact.placeholder.filter->isApplicable($entity$, Oro\Bundle\ActivityBundle\EntityConfig\ActivityScope::VIEW_PAGE)"
