parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     poc_product_entity_design_test
    database_user:     root
    database_password: root
