parameters:
    orocrm_sales.opportunity.form.type.class: OroCRM\Bundle\SalesBundle\Form\Type\OpportunityType
    orocrm_sales.opportunity.form.type.api.class: OroCRM\Bundle\SalesBundle\Form\Type\OpportunityApiType
    orocrm_sales.lead_to_opportunity.form.type.class: OroCRM\Bundle\SalesBundle\Form\Type\LeadToOpportunityType
    orocrm_sales.opportunity.form.handler.class: OroCRM\Bundle\SalesBundle\Form\Handler\OpportunityHandler
    orocrm_sales.lead_to_opportunity.form.handler.class: OroCRM\Bundle\SalesBundle\Form\Handler\LeadToOpportunityHandler

    orocrm_sales.lead.form.type.class: OroCRM\Bundle\SalesBundle\Form\Type\LeadType
    orocrm_sales.lead.address.form.type.class: OroCRM\Bundle\SalesBundle\Form\Type\LeadAddressType
    orocrm_sales.lead.form.type.api.class: OroCRM\Bundle\SalesBundle\Form\Type\LeadApiType
    orocrm_sales.lead.form.handler.class: OroCRM\Bundle\SalesBundle\Form\Handler\LeadHandler
    orocrm_sales.lead_phone.form.type.class: OroCRM\Bundle\SalesBundle\Form\Type\LeadPhoneType
    orocrm_sales.lead_phone.form.handler.class: OroCRM\Bundle\SalesBundle\Form\Handler\LeadPhoneHandler

    orocrm_sales.form.type.lead_select.class:        OroCRM\Bundle\SalesBundle\Form\Type\LeadSelectType
    orocrm_sales.form.type.opportunity_select.class: OroCRM\Bundle\SalesBundle\Form\Type\OpportunitySelectType
    orocrm_sales.form.type.b2bcustomer_select.class: OroCRM\Bundle\SalesBundle\Form\Type\B2bCustomerSelectType

    orocrm_sales.salesfunnel.form.type.class: OroCRM\Bundle\SalesBundle\Form\Type\SalesFunnelType
    orocrm_sales.salesfunnel.form.type.api.class: OroCRM\Bundle\SalesBundle\Form\Type\SalesFunnelApiType
    orocrm_sales.salesfunnel.form.handler.class: OroCRM\Bundle\SalesBundle\Form\Handler\SalesFunnelHandler

    orocrm_sales.b2bcustomer.form.type.class: OroCRM\Bundle\SalesBundle\Form\Type\B2bCustomerType
    orocrm_sales.b2bcustomer.form.type.api.class: OroCRM\Bundle\SalesBundle\Form\Type\B2bCustomerApiType
    orocrm_sales.b2bcustomer.form.handler.class: OroCRM\Bundle\SalesBundle\Form\Handler\B2bCustomerHandler

    orocrm_sales.mailbox_process.lead.type.class: OroCRM\Bundle\SalesBundle\Form\Type\LeadMailboxProcessSettingsType
    orocrm_sales.lead_mailbox_process_source.type.class: OroCRM\Bundle\SalesBundle\Form\Type\LeadMailboxProcessSourceType

    orocrm_sales.lead_data_channel_aware_select.type.class: OroCRM\Bundle\SalesBundle\Form\Type\LeadDataChannelAwareSelectType
    orocrm_sales.entity_data_channel_aware_select.type.class: OroCRM\Bundle\SalesBundle\Form\Type\EntityDataChannelAwareSelectType
    orocrm_sales.opportunity_data_channel_aware_select.type.class: OroCRM\Bundle\SalesBundle\Form\Type\OpportunityDataChannelAwareSelectType

    orocrm_sales.lead_email.type.class: OroCRM\Bundle\SalesBundle\Form\Type\LeadEmailType
    orocrm_sales.lead_email.handler.class: OroCRM\Bundle\SalesBundle\Form\Handler\LeadEmailHandler

services:
    orocrm_sales.opportunity.form.type:
        class: %orocrm_sales.opportunity.form.type.class%
        tags:
            - { name: form.type, alias: orocrm_sales_opportunity }

    orocrm_sales.opportunity.form.type.api:
        class: %orocrm_sales.opportunity.form.type.api.class%
        tags:
            - { name: form.type, alias: orocrm_sales_opportunity_api }

    orocrm_sales.lead_to_opportunity.form.type:
        class: %orocrm_sales.lead_to_opportunity.form.type.class%
        tags:
            - { name: form.type, alias: orocrm_sales_lead_to_opportunity }

    orocrm_sales.opportunity.form:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - "orocrm_sales_opportunity_form"
            - "orocrm_sales_opportunity"

    orocrm_sales.opportunity.form.api:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - "opportunity"
            - "orocrm_sales_opportunity_api"

    orocrm_sales.lead_to_opportunity.form:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - "orocrm_sales_lead_to_opportunity_form"
            - "orocrm_sales_lead_to_opportunity"

    orocrm_sales.opportunity.form.handler:
        class: %orocrm_sales.opportunity.form.handler.class%
        scope: request
        arguments:
            - "@orocrm_sales.opportunity.form"
            - "@request"
            - "@doctrine.orm.entity_manager"
            - "@orocrm_channel.provider.request_channel"

    orocrm_sales.lead_to_opportunity.form.handler:
        class: %orocrm_sales.lead_to_opportunity.form.handler.class%
        scope: request
        arguments:
            - "@orocrm_sales.lead_to_opportunity.form"
            - "@request"
            - "@doctrine.orm.entity_manager"
            - "@orocrm_channel.provider.request_channel"
            - "@orocrm_sales.provider.lead_to_opportunity"

    orocrm_sales.opportunity.form.handler.api:
        class: %orocrm_sales.opportunity.form.handler.class%
        scope: request
        arguments:
            - "@orocrm_sales.opportunity.form.api"
            - "@request"
            - "@doctrine.orm.entity_manager"
            - "@orocrm_channel.provider.request_channel"

    orocrm_sales.lead.form.type:
        class: %orocrm_sales.lead.form.type.class%
        tags:
            - { name: form.type, alias: orocrm_sales_lead }

    orocrm_sales.lead.address.form.type:
        class: %orocrm_sales.lead.address.form.type.class%
        tags:
            - { name: form.type, alias: orocrm_sales_lead_address }

    orocrm_sales.lead.form.type.api:
        class: %orocrm_sales.lead.form.type.api.class%
        tags:
            - { name: form.type, alias: orocrm_sales_lead_api }

    orocrm_sales.lead.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "orocrm_sales_lead_form"
            - "orocrm_sales_lead"

    orocrm_sales.lead.form.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "lead"
            - "orocrm_sales_lead_api"

    orocrm_sales.lead.form.handler:
        class: %orocrm_sales.lead.form.handler.class%
        scope: request
        arguments:
            - "@orocrm_sales.lead.form"
            - "@request"
            - "@doctrine.orm.entity_manager"
            - "@orocrm_channel.provider.request_channel"

    orocrm_sales.lead.form.handler.api:
        class: %orocrm_sales.lead.form.handler.class%
        scope: request
        arguments:
            - "@orocrm_sales.lead.form.api"
            - "@request"
            - "@doctrine.orm.entity_manager"
            - "@orocrm_channel.provider.request_channel"

    orocrm_sales.lead_address.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "orocrm_sales_lead_address_form"
            - "orocrm_sales_lead_address"
            - ~
            - { data_class: %orocrm_sales.leadaddress.entity.class% }

    orocrm_sales.lead_address.form.handler:
        class: %oro_address.form.handler.address.class%
        scope: request
        arguments:
            - "@orocrm_sales.lead_address.form"
            - "@request"
            - "@doctrine.orm.entity_manager"

    orocrm_sales.form.type.opportunity_select:
        class: %orocrm_sales.form.type.opportunity_select.class%
        tags:
            - { name: form.type, alias: orocrm_sales_opportunity_select }

    orocrm_sales.form.type.lead_select:
        class: %orocrm_sales.form.type.lead_select.class%
        tags:
            - { name: form.type, alias: "orocrm_sales_lead_select" }

    orocrm_sales.form.type.b2bcustomer_select:
        class: %orocrm_sales.form.type.b2bcustomer_select.class%
        tags:
            - { name: form.type, alias: orocrm_sales_b2bcustomer_select }

    orocrm_sales.form.type.b2bcustomer_with_channel_select:
        class: OroCRM\Bundle\SalesBundle\Form\Type\B2bCustomerWithChannelSelectType
        tags:
            - { name: form.type, alias: orocrm_sales_b2bcustomer_with_channel_select }

    orocrm_sales.salesfunnel.form.type:
        class: %orocrm_sales.salesfunnel.form.type.class%
        tags:
            - { name: form.type, alias: "orocrm_sales_funnel" }

    orocrm_sales.salesfunnel.form.type.api:
        class: %orocrm_sales.salesfunnel.form.type.api.class%
        tags:
            - { name: form.type, alias: "orocrm_sales_salesfunnel_api" }

    orocrm_sales.salesfunnel.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "orocrm_sales_salesfunnel_form"
            - "orocrm_sales_funnel"

    orocrm_sales.salesfunnel.form.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "salesfunnel"
            - "orocrm_sales_salesfunnel_api"

    orocrm_sales.salesfunnel.form.handler:
        class: %orocrm_sales.salesfunnel.form.handler.class%
        scope: request
        arguments:
            - "@orocrm_sales.salesfunnel.form"
            - "@request"
            - "@doctrine.orm.entity_manager"

    orocrm_sales.salesfunnel.form.handler.api:
        class: %orocrm_sales.salesfunnel.form.handler.class%
        scope: request
        arguments:
            - "@orocrm_sales.salesfunnel.form.api"
            - "@request"
            - "@doctrine.orm.entity_manager"

    orocrm_sales.b2bcustomer.form.type:
        class: %orocrm_sales.b2bcustomer.form.type.class%
        tags:
            - { name: form.type, alias: orocrm_sales_b2bcustomer }

    orocrm_sales.b2bcustomer.form.type.api:
        class: %orocrm_sales.b2bcustomer.form.type.api.class%
        tags:
            - { name: form.type, alias: orocrm_sales_b2bcustomer_api }

    orocrm_sales.mailbox_process.lead.type:
        class: %orocrm_sales.mailbox_process.lead.type.class%
        tags:
            - { name: form.type, alias: orocrm_sales_lead_mailbox_process_settings }

    orocrm_sales.lead_mailbox_process_source.type:
        class: %orocrm_sales.lead_mailbox_process_source.type.class%
        arguments:  ["@oro_entity_extend.enum_value_provider"]
        tags:
            - { name: form.type, alias: orocrm_sales_lead_mailbox_process_source }

    orocrm_sales.b2bcustomer.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "orocrm_sales_b2bcustomer_form"
            - "orocrm_sales_b2bcustomer"

    orocrm_sales.b2bcustomer.form.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "b2bcustomer"
            - "orocrm_sales_b2bcustomer_api"

    orocrm_sales.b2bcustomer.form.handler:
        class: %orocrm_sales.b2bcustomer.form.handler.class%
        scope: request
        arguments:
            - "@orocrm_sales.b2bcustomer.form"
            - "@request"
            - "@doctrine.orm.entity_manager"
            - "@orocrm_channel.provider.request_channel"

    orocrm_sales.b2bcustomer.form.handler.api:
        class: %orocrm_sales.b2bcustomer.form.handler.class%
        scope: request
        arguments:
            - "@orocrm_sales.b2bcustomer.form.api"
            - "@request"
            - "@doctrine.orm.entity_manager"
            - "@orocrm_channel.provider.request_channel"

    orocrm_sales.lead_data_channel_aware_select.type:
        class: %orocrm_sales.lead_data_channel_aware_select.type.class%
        tags:
            - { name: form.type, alias: orocrm_sales_lead_data_channel_aware_select }

    orocrm_sales.opportunity_data_channel_aware_select.type:
        class: %orocrm_sales.opportunity_data_channel_aware_select.type.class%
        tags:
            - { name: form.type, alias: orocrm_sales_opportunity_data_channel_aware_select }

    orocrm_sales.type.oppotunity_status_select:
        class: OroCRM\Bundle\SalesBundle\Form\Type\OpportunityStatusSelectType
        arguments:
            - '@oro_entity_extend.enum_value_provider'
        tags:
            - { name: form.type, alias: orocrm_type_widget_opportunity_status_select }

    orocrm_sales.type.lead_status_select:
        class: OroCRM\Bundle\SalesBundle\Form\Type\LeadStatusSelectType
        arguments:
           - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type, alias: orocrm_type_widget_lead_status_select }

    orocrm_sales.widget_config_value.widget_opportunity_status.converter:
        class: OroCRM\Bundle\SalesBundle\Dashboard\Converters\WidgetOpportunityStatusSelectConverter
        arguments:
            - '@oro_security.acl_helper'
            - '@oro_entity.entity_name_resolver'
            - '@oro_entity.doctrine_helper'
            - '@doctrine.orm.entity_manager'
            - 'opportunity_status'
        tags:
            - { name: oro_dashboard.value.converter, alias: 'orocrm_type_widget_opportunity_status_select' }

    orocrm_sales.widget_config_value.widget_lead_status.converter:
        class: OroCRM\Bundle\SalesBundle\Dashboard\Converters\WidgetLeadStatusSelectConverter
        arguments:
            - '@oro_security.acl_helper'
            - '@oro_entity.entity_name_resolver'
            - '@oro_entity.doctrine_helper'
            - '@doctrine.orm.entity_manager'
            - 'OroCRM\Bundle\SalesBundle\Entity\LeadStatus'
        tags:
            - { name: oro_dashboard.value.converter, alias: 'orocrm_type_widget_lead_status_select' }

    orocrm_sales.form.type.lead_phone.type:
        class: %orocrm_sales.lead_phone.form.type.class%
        tags:
            - { name: form.type, alias: orocrm_sales_lead_phone }

    orocrm_sales.form.type.lead_phone.handler:
        class: %orocrm_sales.lead_phone.form.handler.class%
        scope: request
        arguments:
            - "@form.factory"
            - "@request"
            - "@doctrine.orm.entity_manager"
            - "@oro_security.security_facade"

    orocrm_sales.form.type.lead_email.type:
        class: %orocrm_sales.lead_email.type.class%
        tags:
            - { name: form.type, alias: orocrm_sales_lead_email }

    orocrm_sales.form.type.lead_email.handler:
        class: %orocrm_sales.lead_email.handler.class%
        scope: request
        arguments:
            - "@form.factory"
            - "@request"
            - "@doctrine.orm.entity_manager"
            - "@oro_security.security_facade"
