oro_entity:
    virtual_fields:
        Oro\Bundle\AccountBundle\Entity\Account:
            lifetimeValue:
                query:
                    select:
                        expr: SUM(CASE WHEN h.amount is NULL THEN 0 ELSE h.amount END)
                        return_type: money
                    join:
                        left:
                            - { join: Oro\Bundle\ChannelBundle\Entity\LifetimeValueHistory, alias: h, conditionType: WITH, condition: 'h.account = entity AND h.status = true' }
            contactInformation:
                query:
                    select:
                        expr: defaultContactEmails.email
                        return_type: string
                    join:
                        left:
                            - { join: entity.defaultContact, alias: defaultContact }
                            - { join: defaultContact.emails, alias: defaultContactEmails, conditionType: WITH, condition: 'defaultContactEmails.primary = true' }
