placeholders:
    placeholders:
        quick_launchpad_left_column:
            items:
                accounts_launchpad:
                    order: 10
        page_header_stats_after:
            items:
                account_lifetime_value:
                    order: 20

    items:
        accounts_launchpad:
            template: OroAccountBundle:Dashboard:accountsLaunchpad.html.twig
        account_lifetime_value:
            template: OroAccountBundle:Account:lifetimeValue.html.twig
            applicable: '@oro_ui.placeholder.filter->isInstanceOf($entity$, Oro\Bundle\AccountBundle\Entity\Account)'
