placeholders:
    placeholders:
        page_header_stats_after:
            items:
                oro_activity_contact:
                    order: 10

    items:
        oro_activity_contact:
            template: OroActivityContactBundle:ActivityContact:metrics.html.twig
            applicable: "@oro_activity_contact.placeholder.filter->isApplicable($entity$, Oro\\Bundle\\ActivityBundle\\EntityConfig\\ActivityScope::VIEW_PAGE)"
