workflows:
    case_flow:
        steps:
            open:
                label: 'Open'
                order: 10
                allowed_transitions:
                    - start_progress
                    - resolve
                    - close
            in_progress:
                label: 'In progress'
                order: 20
                allowed_transitions:
                    - stop_progress
                    - resolve
                    - close
            resolved:
                label: 'Resolved'
                order: 30
                allowed_transitions:
                    - reopen
                is_final: true
            closed:
                label: 'Closed'
                order: 40
                allowed_transitions:
                    - reopen
                is_final: true
