orocrm_contact_bundle:
    resource:     "@OroCRMContactBundle/Controller"
    type:         annotation
    prefix:       /contact

orocrm_contact_bundle_api:
    resource: "@OroCRMContactBundle/Resources/config/oro/routing_api.yml"
    type: rest
    prefix:       api/rest/{version}
    requirements:
        version:  latest|v1
    defaults:
        version:  latest

# deprecated API routes
oro_api_post_contact_deprecated:
    path:            /api/rest/{version}/contact.{_format}
    methods:         [POST]
    defaults:
        _controller: OroCRM\Bundle\ContactBundle\Controller\Api\Rest\ContactController::postAction
        _format:     json
        version:     latest
    requirements:
        _format:     json|html
        version:     latest|v1

oro_api_post_contactgroup_deprecated:
    path:            /api/rest/{version}/contactgroup.{_format}
    methods:         [POST]
    defaults:
        _controller: OroCRM\Bundle\ContactBundle\Controller\Api\Rest\ContactGroupController::postAction
        _format:     json
        version:     latest
    requirements:
        _format:     json|html
        version:     latest|v1
