connector:
    name: oro_importexport
    jobs:
        mage_customer_import:
            title: "Customer import from Magento"
            type:  import
            steps:
                import:
                    title:     import
                    class:     Oro\Bundle\ImportExportBundle\Job\Step\PostProcessItemStep
                    services:
                        reader:    orocrm_magento.mage.customer_connector
                        processor: oro_importexport.processor.import_delegate
                        writer:    orocrm_magento.writer.proxy_entity_writer
                        job_executor: oro_importexport.job_executor
                    parameters:
                        batch_size: 25
                        post_processing_jobs: mage_customer_load_customer_info
                        context_shared_keys: postProcessCustomerIds

        mage_customer_load_customer_info:
            title: "Import customers info and addresses"
            type:  import
            steps:
                load_customer_info:
                    title:     import
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.reader.customer_info
                        processor: orocrm_magento.importexport.processor.import_customer
                        writer:    orocrm_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25

        magento_customer_export:
            title: 'Export Magento Customer to Magento'
            type: export
            steps:
                export:
                    title: export
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.importexport.reader.entity
                        processor: orocrm_magento.importexport.processor.customer_export
                        writer:    orocrm_magento.importexport.writer.customer
                    parameters:
                        batch_size: 1
                import_merged_data:
                    title: export
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.reader.context_customer_export
                        processor: orocrm_magento.importexport.processor.import_customer
                        writer:    orocrm_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 1

        magento_newsletter_subscriber_export:
            title: 'Export Newsletter Subscriber to Magento'
            type: export
            steps:
                export:
                    title: export
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.importexport.reader.entity
                        processor: orocrm_magento.importexport.processor.newsletter_subscriber_export
                        writer:    orocrm_magento.importexport.writer.newsletter_subscriber
                    parameters:
                        batch_size: 1
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.reader.context_newsletter_subscriber_export
                        processor: orocrm_magento.importexport.processor.import_newsletter_subscriber_with_customer
                        writer:    orocrm_magento.writer.proxy_entity_writer

        magento_customer_address_export:
            title: 'Export Magento Customer Address to Magento'
            type: export
            steps:
                export:
                    title: export
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.importexport.reader.entity
                        processor: orocrm_magento.importexport.processor.customer_address_export
                        writer:    orocrm_magento.importexport.writer.customer_address
                    parameters:
                        batch_size: 1
                import_merged_data:
                    title: export
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.reader.context_customer_address_export
                        processor: orocrm_magento.importexport.processor.import_customer_address
                        writer:    orocrm_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 1

        mage_region_import:
            title: "Region import from Magento"
            type:  import
            steps:
                import:
                    title:     import
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.mage.region_connector
                        processor: oro_importexport.processor.import_delegate
                        writer:    orocrm_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 100

        mage_order_import:
            title: "Order import from Magento"
            type:  import
            steps:
                import_with_existing_customers:
                    title:     import
                    class:     Oro\Bundle\ImportExportBundle\Job\Step\PostProcessItemStep
                    services:
                        reader:    orocrm_magento.mage.order_connector
                        processor: orocrm_magento.importexport.processor.import_order_with_customer
                        writer:    orocrm_magento.writer.proxy_entity_writer
                        job_executor: oro_importexport.job_executor
                    parameters:
                        batch_size: 25
                        post_processing_jobs: mage_order_import_post_process_customers_and_info
                        context_shared_keys: postProcessGuestCustomers,postProcessOrders,postProcessCustomerIds,postProcessCartsIds,postProcessOrderIds

        mage_order_import_post_process_customers_and_info:
            title: "Import customers and postponded orders"
            type:  import
            steps:
                import_customers:
                    title:     import
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.reader.context_customer.order
                        processor: orocrm_magento.importexport.processor.import_customer
                        writer:    orocrm_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25
                import_guest_customers:
                    title:     import
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.reader.context_guest_customer
                        processor: orocrm_magento.importexport.processor.import_guest_customer
                        writer:    orocrm_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25
                import_carts:
                    title:     import
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.reader.context_cart.order
                        processor: orocrm_magento.importexport.processor.import_cart
                        writer:    orocrm_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25
                import_with_new_customers:
                    title:     import
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.reader.context_order
                        processor: orocrm_magento.importexport.processor.context_order
                        writer:    orocrm_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25
                load_customer_info:
                    title:     import
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.reader.customer_info
                        processor: orocrm_magento.importexport.processor.import_customer
                        writer:    orocrm_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25
                load_order_info:
                    title:     import
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.reader.order_info
                        processor: orocrm_magento.importexport.processor.import_order
                        writer:    orocrm_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25

        mage_cart_import:
            title: "Cart(quote) import from Magento"
            type:  import
            steps:
                import_with_existing_customers:
                    title:     import
                    class:     Oro\Bundle\ImportExportBundle\Job\Step\PostProcessItemStep
                    services:
                        reader:    orocrm_magento.mage.cart_connector
                        processor: orocrm_magento.importexport.processor.import_cart_with_customer
                        writer:    orocrm_magento.writer.proxy_entity_writer
                        job_executor: oro_importexport.job_executor
                    parameters:
                        batch_size: 25
                        post_processing_jobs: mage_cart_import_post_process_customers
                        context_shared_keys: postProcessCarts,postProcessCustomerIds

        mage_cart_import_post_process_customers:
            title: "Import customers and postponded carts"
            type:  import
            steps:
                import_customers:
                    title:     import
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.reader.context_customer.cart
                        processor: orocrm_magento.importexport.processor.import_customer
                        writer:    orocrm_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25
                import_with_new_customers:
                    title:     import
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.reader.context_cart
                        processor: orocrm_magento.importexport.processor.context_cart
                        writer:    orocrm_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25
                load_customer_info:
                    title:     import
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.reader.customer_info
                        processor: orocrm_magento.importexport.processor.import_customer
                        writer:    orocrm_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25

        mage_newsletter_subscriber_import:
            title: "Import newsletter subscribers from Magento"
            type:  import
            steps:
                import:
                    title:     import
                    class:     Oro\Bundle\ImportExportBundle\Job\Step\PostProcessItemStep
                    services:
                        reader:    orocrm_magento.mage.newsletter_subscriber_connector
                        processor: orocrm_magento.importexport.processor.import_newsletter_subscriber_with_customer
                        writer:    orocrm_magento.writer.proxy_entity_writer
                        job_executor: oro_importexport.job_executor
                    parameters:
                        batch_size: 25
                        post_processing_jobs: mage_newsletter_subscriber_post_process_customers
                        context_shared_keys: postProcessSubscribers,postProcessCustomerIds

        mage_newsletter_subscriber_import_initial:
            title: "Initial import newsletter subscribers from Magento"
            type:  import
            steps:
                import:
                    title:     import
                    class:     Oro\Bundle\ImportExportBundle\Job\Step\PostProcessItemStep
                    services:
                        reader:    orocrm_magento.mage.newsletter_subscriber_connector_initial
                        processor: orocrm_magento.importexport.processor.import_newsletter_subscriber_with_customer
                        writer:    orocrm_magento.importexport.writer.initial_sync.newsletter_subscriber
                        job_executor: oro_importexport.job_executor
                    parameters:
                        batch_size: 25
                        post_processing_jobs: mage_newsletter_subscriber_post_process_customers
                        context_shared_keys: postProcessSubscribers,postProcessCustomerIds

        mage_newsletter_subscriber_post_process_customers:
            title: "Import customers and postponded newsletter subscribers"
            type:  import
            steps:
                import_customers:
                    title:     import
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.reader.context_customer.newsletter_subscriber
                        processor: orocrm_magento.importexport.processor.import_customer
                        writer:    orocrm_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25
                import_posponded_subscribers:
                    title:     import
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.reader.context_newsletter_subscriber
                        processor: orocrm_magento.importexport.processor.context_newsletter_subscriber
                        writer:    orocrm_magento.importexport.writer.initial_sync.newsletter_subscriber
                    parameters:
                        batch_size: 25
                load_customer_info:
                    title:     import
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.reader.customer_info
                        processor: orocrm_magento.importexport.processor.import_customer
                        writer:    orocrm_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25

        mage_store_import:
            title: "Store import from Magento"
            type:  import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.mage.store
                        processor: orocrm_magento.importexport.processor.store
                        writer:    orocrm_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25

        mage_website_import:
            title: "Website import from Magento"
            type:  import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.mage.website
                        processor: orocrm_magento.importexport.processor.website
                        writer:    orocrm_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25

        mage_customer_group_import:
            title: "Customer groups import from Magento"
            type:  import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.mage.customer_group
                        processor: orocrm_magento.importexport.processor.customer_group
                        writer:    orocrm_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25
