placeholders:
    placeholders:
        view_content_data_additional_information:
            items:
                oro_user_cases_grid: ~
                oro_account_cases_grid: ~
                oro_contact_cases_grid: ~

    items:
        oro_user_cases_grid:
            template: OroCaseBundle:Case:userCases.html.twig
            applicable: "@oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)"
        oro_account_cases_grid:
            template: OroCaseBundle:Case:accountCases.html.twig
            applicable: "@oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_account.account.entity.class%)"
        oro_contact_cases_grid:
            template: OroCaseBundle:Case:contactCases.html.twig
            applicable: "@oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_contact.entity.class%)"
