datagrids:
    orcrm-contact-requests-grid:
        extended_entity_name: %oro_contact_us.contactrequest.entity.class%
        acl_resource: oro_contactus_request_view
        source:
            type: orm
            query:
                select:
                    - cr.id
                    - cr.firstName
                    - cr.lastName
                    - cr.emailAddress
                    - cr.phone
                    - cr.createdAt
                from:
                    - { table: %oro_contact_us.contactrequest.entity.class%, alias: cr }
        columns:
            firstName:
                label:         oro.contactus.contactrequest.first_name.label
            lastName:
                label:         oro.contactus.contactrequest.last_name.label
            phone:
                label:         oro.contactus.contactrequest.phone.label
                frontend_type: phone
            emailAddress:
                label:         oro.contactus.contactrequest.email_address.label
            createdAt:
                frontend_type: datetime
                label:         oro.ui.created_at
        sorters:
            columns:
                firstName:
                    data_name: cr.firstName
                lastName:
                    data_name: cr.lastName
                phone:
                    data_name: cr.phone
                emailAddress:
                    data_name: cr.emailAddress
                createdAt:
                    data_name: cr.createdAt
            default:
                createdAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
        filters:
            columns:
                firstName:
                    type:      string
                    data_name: cr.firstName
                lastName:
                    type:      string
                    data_name: cr.lastName
                phone:
                    type:      string
                    data_name: cr.phone
                emailAddress:
                    type:      string
                    data_name: cr.emailAddress
                createdAt:
                    type:      datetime
                    data_name: cr.createdAt
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_contactus_request_view
                params:     [ id ]
            update_link:
                type:       url
                route:      oro_contactus_request_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_contactus_request_delete
                params:     [ id ]
        actions:
            view:
                acl_resource: oro_contactus_request_view
                type:         navigate
                label:        oro.grid.action.view
                icon:         eye
                link:         view_link
                rowAction:    true
            update:
                acl_resource: oro_contactus_request_edit
                type:         navigate
                label:        oro.grid.action.update
                icon:         edit
                link:         update_link
            delete:
                acl_resource: oro_contactus_request_delete
                type:         delete
                label:        oro.grid.action.delete
                icon:         trash
                link:         delete_link
        options:
            entityHint: contact requests
            entity_pagination: true
    orcrm-contact-reasons-grid:
        acl_resource: oro_contactus_reason_view
        options:
            entity_pagination: true
        source:
            type:         orm
            query:
                select:
                    - contactReason.id
                    - contactReason.label
                from:
                    - { table: '%oro_contact_us.contactreason.entity.class%', alias: contactReason }
        columns:
            label:
                label: oro.contactus.contactreason.label.label
        properties:
            id: ~
            update_link:
                type:   url
                route:  oro_contactus_reason_update
                params: [ id ]
            delete_link:
                type:   url
                route:  oro_contactus_reason_delete
                params: [ id ]
        actions:
            update:
                acl_resource: oro_contactus_reason_edit
                type:         navigate
                label:        oro.grid.action.update
                icon:         edit
                link:         update_link
                rowAction:    true
            delete:
                acl_resource: oro_contactus_reason_delete
                type:         delete
                label:        oro.grid.action.delete
                icon:         trash
                link:         delete_link
