orocrm_sales_opportunity_api:
    resource: "@OroCRMSalesBundle/Controller/Api/Rest/OpportunityController.php"
    type:     rest

orocrm_sales_lead_api:
    resource: "@OroCRMSalesBundle/Controller/Api/Rest/LeadController.php"
    type:     rest

orocrm_sales_salesfunnel_api:
    resource: "@OroCRMSalesBundle/Controller/Api/Rest/SalesFunnelController.php"
    type:     rest

orocrm_sales_b2bcustomer_api:
    resource: "@OroCRMSalesBundle/Controller/Api/Rest/B2bCustomerController.php"
    type:     rest

orocrm_sales_b2bcustomer_email_api:
    resource: "@OroCRMSalesBundle/Controller/Api/Rest/B2bCustomerEmailController.php"
    type:     rest

orocrm_sales_b2bcustomer_phone_api:
    resource: "@OroCRMSalesBundle/Controller/Api/Rest/B2bCustomerPhoneController.php"
    type:     rest
