oro_entity:
    exclusions:
        - { entity: Oro\Bundle\SalesBundle\Entity\Opportunity, field: baseBudgetAmountValue }
        - { entity: Oro\Bundle\SalesBundle\Entity\Opportunity, field: baseCloseRevenueValue }
        - { entity: Oro\Bundle\SalesBundle\Entity\Opportunity, field: customerAssociation }
        - { entity: Oro\Bundle\SalesBundle\Entity\Lead, field: customerAssociation }

    virtual_fields:
        Oro\Bundle\SalesBundle\Entity\B2bCustomer:
            primaryEmail:
                query:
                    select:
                        expr: emails.email
                        return_type: string
                    join:
                        left:
                            - { join: entity.emails, alias: emails, conditionType: WITH, condition: 'emails.primary = true' }
            primaryPhone:
                query:
                    select:
                        expr: phones.phone
                        return_type: string
                    join:
                        left:
                            - { join: entity.phones, alias: phones, conditionType: WITH, condition: 'phones.primary = true' }
            contactInformation:
                query:
                    select:
                        expr: emails.email
                        return_type: string
                    join:
                        left:
                            - { join: entity.emails, alias: emails, conditionType: WITH, condition: 'emails.primary = true' }
        Oro\Bundle\SalesBundle\Entity\Lead:
            primaryEmail:
                query:
                    select:
                        expr: emails.email
                        return_type: string
                    join:
                        left:
                            - { join: entity.emails, alias: emails, conditionType: WITH, condition: 'emails.primary = true' }
            primaryPhone:
                query:
                    select:
                        expr: phones.phone
                        return_type: string
                    join:
                        left:
                            - { join: entity.phones, alias: phones, conditionType: WITH, condition: 'phones.primary = true' }
            contactInformation:
                query:
                    select:
                        expr: emails.email
                        return_type: string
                    join:
                        left:
                            - { join: entity.emails, alias: emails, conditionType: WITH, condition: 'emails.primary = true' }

    virtual_relations:
        Oro\Bundle\SalesBundle\Entity\Lead:
            account:
                relation_type: oneToMany
                related_entity_name: Oro\Bundle\AccountBundle\Entity\Account
                label: oro.account.entity_label
                target_join_alias: lead_account
                query:
                    join:
                        left:
                            - { join: entity.customerAssociation, alias: lead_ca }
                            - { join: lead_ca.account, alias: lead_account }
            primaryAddr:
                relation_type: oneToOne
                related_entity_name: Oro\Bundle\SalesBundle\Entity\LeadAddress
                label: oro.sales.lead.primary_addr.label
                query:
                    join:
                        left:
                            - { join: entity.addresses, alias: addresses, conditionType: WITH, condition: 'addresses.primary = true' }
        Oro\Bundle\SalesBundle\Entity\Opportunity:
            account:
                relation_type: oneToMany
                related_entity_name: Oro\Bundle\AccountBundle\Entity\Account
                label: oro.account.entity_label
                target_join_alias: opportunity_account
                query:
                    join:
                        left:
                            - { join: entity.customerAssociation, alias: opportunity_ca }
                            - { join: opportunity_ca.account, alias: opportunity_account }

    entity_aliases:
        Oro\Bundle\SalesBundle\Entity\Customer:
            alias:        salescustomer
            plural_alias: salescustomers
        Extend\Entity\EV_Opportunity_Status:
            alias:        opportunitystatus
            plural_alias: opportunitystatuses
        Extend\Entity\EV_Lead_Status:
            alias:        leadstatus
            plural_alias: leadstatuses
