# Magento integration is disabled in CRM-9202
api:
    entities:
#        Oro\Bundle\MagentoBundle\Entity\Address:
#            documentation_resource: '@OroMagentoBundle/Resources/doc/api/address.md'
#            fields:
#                createdAt:
#                    property_path: created
#                updatedAt:
#                    property_path: updated
#                customRegion:
#                    exclude: false # set manually because this field is marked as excluded in entity.yml
#                    property_path: regionText
#
#        Oro\Bundle\MagentoBundle\Entity\Cart:
#            documentation_resource: '@OroMagentoBundle/Resources/doc/api/cart.md'
#            fields:
#                createdAt:
#                    form_options:
#                        mapped: true # set manually because by default createdAt field is read-only
#                updatedAt:
#                    form_options:
#                        mapped: true # set manually because by default updatedAt field is read-only
#
#        Oro\Bundle\MagentoBundle\Entity\CartAddress:
#            documentation_resource: '@OroMagentoBundle/Resources/doc/api/cart_address.md'
#            fields:
#                createdAt:
#                    property_path: created
#                updatedAt:
#                    property_path: updated
#                customRegion:
#                    exclude: false # set manually because this field is marked as excluded in entity.yml
#                    property_path: regionText
#
#        Oro\Bundle\MagentoBundle\Entity\CartItem:
#            documentation_resource: '@OroMagentoBundle/Resources/doc/api/cart_item.md'
#            fields:
#                createdAt:
#                    form_options:
#                        mapped: true # set manually because by default createdAt field is read-only
#                updatedAt:
#                    form_options:
#                        mapped: true # set manually because by default updatedAt field is read-only
#
        Oro\Bundle\MagentoBundle\Entity\CartStatus: { exclude: true}
#            documentation_resource: '@OroMagentoBundle/Resources/doc/api/cart.md'
#
#        Oro\Bundle\MagentoBundle\Entity\Customer:
#            documentation_resource: '@OroMagentoBundle/Resources/doc/api/customer.md'
#            fields:
#                createdAt:
#                    form_options:
#                        mapped: true # set manually because by default createdAt field is read-only
#                updatedAt:
#                    form_options:
#                        mapped: true # set manually because by default updatedAt field is read-only
#                orders:
#                    exclude: true
#                carts:
#                    exclude: true
#            subresources:
#                orders:
#                    actions:
#                        update_relationship: false
#                        add_relationship: false
#                        delete_relationship: false
#                carts:
#                    actions:
#                        update_relationship: false
#                        add_relationship: false
#                        delete_relationship: false
#
#        Oro\Bundle\MagentoBundle\Entity\Order:
#            documentation_resource: '@OroMagentoBundle/Resources/doc/api/order.md'
#            fields:
#                createdAt:
#                    form_options:
#                        mapped: true # set manually because by default createdAt field is read-only
#                updatedAt:
#                    form_options:
#                        mapped: true # set manually because by default updatedAt field is read-only
#            subresources:
#                orderNotes:
#                    actions:
#                        update_relationship: false
#                        add_relationship: false
#                        delete_relationship: false
#
#        Oro\Bundle\MagentoBundle\Entity\OrderAddress:
#            documentation_resource: '@OroMagentoBundle/Resources/doc/api/order_address.md'
#            fields:
#                customRegion:
#                    exclude: false # set manually because this field is marked as excluded in entity.yml
#                    property_path: regionText
#
#        Oro\Bundle\MagentoBundle\Entity\OrderItem:
#            documentation_resource: '@OroMagentoBundle/Resources/doc/api/order_item.md'
#
#        Oro\Bundle\MagentoBundle\Entity\OrderNote:
#            documentation_resource: '@OroMagentoBundle/Resources/doc/api/order_note.md'
#            actions:
#                create: false
#                update: false
#                delete: false
#                delete_list: false
#                get_subresource: false
#                get_relationship: false
#                update_relationship: false
#                add_relationship: false
#                delete_relationship: false
#
#        Oro\Bundle\MagentoBundle\Entity\CreditMemo:
#            documentation_resource: '@OroMagentoBundle/Resources/doc/api/credit_memo.md'
#            fields:
#                createdAt:
#                    form_options:
#                        mapped: true # set manually because by default createdAt field is read-only
#                updatedAt:
#                    form_options:
#                        mapped: true # set manually because by default updatedAt field is read-only
#
        Extend\Entity\EV_Creditmemo_Status: { exclude: true}
#            documentation_resource: '@OroMagentoBundle/Resources/doc/api/credit_memo.md'
#
#        Oro\Bundle\MagentoBundle\Entity\CreditMemoItem:
#            documentation_resource: '@OroMagentoBundle/Resources/doc/api/credit_memo_item.md'
#
#        Oro\Bundle\MagentoBundle\Entity\Product:
#            documentation_resource: '@OroMagentoBundle/Resources/doc/api/product.md'
#            fields:
#                createdAt:
#                    form_options:
#                        mapped: true # set manually because by default createdAt field is read-only
#                updatedAt:
#                    form_options:
#                        mapped: true # set manually because by default updatedAt field is read-only
#
#        Oro\Bundle\MagentoBundle\Entity\Region:
#            documentation_resource: '@OroMagentoBundle/Resources/doc/api/region.md'
#
#        Oro\Bundle\MagentoBundle\Entity\Store:
#            documentation_resource: '@OroMagentoBundle/Resources/doc/api/store.md'
#
#        Oro\Bundle\MagentoBundle\Entity\Website:
#            documentation_resource: '@OroMagentoBundle/Resources/doc/api/website.md'
#
#        # remove this exclusion when NewsletterSubscriber entity will be enabled for API
        Extend\Entity\EV_Mage_Subscr_Status: { exclude: true}
