# Magento integration is disabled in CRM-9202
#api:
#    entities:
#        Oro\Bundle\MagentoBundle\Entity\Cart:
#            fields:
#                shippingAddress:
#                    collapse: false
#                    fields:
#                        owner:
#                            exclude: true
#                billingAddress:
#                    collapse: false
#                    fields:
#                        owner:
#                            exclude: true
#
#        Oro\Bundle\MagentoBundle\Entity\Order:
#            fields:
#                addresses:
#                    collapse: false
#                    fields:
#                        owner:
#                            exclude: true
#                        types:
#                            order_by:
#                                name: ASC
#
#        Oro\Bundle\MagentoBundle\Entity\Customer:
#            fields:
#                addresses:
#                    collapse: false
#                    fields:
#                        owner:
#                            exclude: true
#                        types:
#                            order_by:
#                                name: ASC
