oro_entity:
    # Hide all Magento entities because Magento integration is disabled in CRM-9202
    exclusions:
        - { entity: Oro\Bundle\MagentoBundle\Entity\Address }
        - { entity: Oro\Bundle\MagentoBundle\Entity\Cart }
        - { entity: Oro\Bundle\MagentoBundle\Entity\CartAddress }
        - { entity: Oro\Bundle\MagentoBundle\Entity\CartItem }
        - { entity: Oro\Bundle\MagentoBundle\Entity\CartStatus }
        - { entity: Oro\Bundle\MagentoBundle\Entity\CreditMemo }
        - { entity: Oro\Bundle\MagentoBundle\Entity\CreditMemoItem }
        - { entity: Oro\Bundle\MagentoBundle\Entity\Customer }
        - { entity: Oro\Bundle\MagentoBundle\Entity\CustomerGroup }
        - { entity: Oro\Bundle\MagentoBundle\Entity\NewsletterSubscriber }
        - { entity: Oro\Bundle\MagentoBundle\Entity\Order }
        - { entity: Oro\Bundle\MagentoBundle\Entity\OrderAddress }
        - { entity: Oro\Bundle\MagentoBundle\Entity\OrderItem }
        - { entity: Oro\Bundle\MagentoBundle\Entity\OrderNote }
        - { entity: Oro\Bundle\MagentoBundle\Entity\Product }
        - { entity: Oro\Bundle\MagentoBundle\Entity\Store }
        - { entity: Oro\Bundle\MagentoBundle\Entity\Website }

    virtual_relations:
        Oro\Bundle\MagentoBundle\Entity\Customer:
            primaryAddr:
                relation_type: oneToOne
                related_entity_name: Oro\Bundle\MagentoBundle\Entity\Address
                label: oro.magento.customer.primary_addr.label
                query:
                    join:
                        left:
                            - { join: entity.addresses, alias: addresses, conditionType: 'WITH', condition: 'addresses.primary = true' }
    virtual_fields:
        Oro\Bundle\MagentoBundle\Entity\Customer:
            contactInformation:
                query:
                    select:
                        expr:         entity.email
                        return_type:  string
        Oro\Bundle\MagentoBundle\Entity\Cart:
            contactInformation:
                query:
                    select:
                        expr:         entity.email
                        return_type:  string
        Oro\Bundle\MagentoBundle\Entity\NewsletterSubscriber:
            contactInformation:
                query:
                    select:
                        expr:         entity.email
                        return_type:  string

    entity_aliases:
        Oro\Bundle\MagentoBundle\Entity\Address:
            alias:        magentoaddress
            plural_alias: magentoaddresses
        Oro\Bundle\MagentoBundle\Entity\Cart:
            alias:        magentocart
            plural_alias: magentocarts
        Oro\Bundle\MagentoBundle\Entity\CartAddress:
            alias:        magentocartaddress
            plural_alias: magentocartaddresses
        Oro\Bundle\MagentoBundle\Entity\CartItem:
            alias:        magentocartitem
            plural_alias: magentocartitems
        Oro\Bundle\MagentoBundle\Entity\CartStatus:
            alias:        magentocartstatus
            plural_alias: magentocartstatuses
        Oro\Bundle\MagentoBundle\Entity\Customer:
            alias:        magentocustomer
            plural_alias: magentocustomers
        Oro\Bundle\MagentoBundle\Entity\CustomerGroup:
            alias:        magentocustomergroup
            plural_alias: magentocustomergroups
        Oro\Bundle\MagentoBundle\Entity\NewsletterSubscriber:
            alias:        magentonewslettersubscriber
            plural_alias: magentonewslettersubscribers
        Oro\Bundle\MagentoBundle\Entity\Order:
            alias:        magentoorder
            plural_alias: magentoorders
        Oro\Bundle\MagentoBundle\Entity\OrderAddress:
            alias:        magentoorderaddress
            plural_alias: magentoorderaddresses
        Oro\Bundle\MagentoBundle\Entity\OrderItem:
            alias:        magentoorderitem
            plural_alias: magentoorderitems
        Oro\Bundle\MagentoBundle\Entity\CreditMemo:
            alias:        magentocreditmemo
            plural_alias: magentocreditmemos
        Oro\Bundle\MagentoBundle\Entity\CreditMemoItem:
            alias:        magentocreditmemoitem
            plural_alias: magentocreditmemoitems
        Oro\Bundle\MagentoBundle\Entity\Product:
            alias:        magentoproduct
            plural_alias: magentoproducts
        Oro\Bundle\MagentoBundle\Entity\Region:
            alias:        magentoregion
            plural_alias: magentoregions
        Oro\Bundle\MagentoBundle\Entity\Store:
            alias:        magentostore
            plural_alias: magentostores
        Oro\Bundle\MagentoBundle\Entity\Website:
            alias:        magentowebsite
            plural_alias: magentowebsites
        Extend\Entity\EV_Mage_Subscr_Status:
            alias:        magentonewslettersubscriberstatus
            plural_alias: magentonewslettersubscriberstatuses
        Extend\Entity\EV_Creditmemo_Status:
            alias:        magentocreditmemostatus
            plural_alias: magentocreditmemostatuses
        Oro\Bundle\MagentoBundle\Entity\OrderNote:
            alias:        magentoordernote
            plural_alias: magentoordernotes
