oro_menu_config:
    items:
        task_list:
            label: 'orocrm.task.entity_plural_label'
            route: 'orocrm_task_index'
            extras:
                position: 10
                routes: ['orocrm_task_update', 'orocrm_task_create', 'orocrm_task_view']
                description: 'orocrm.task.menu.task_list.description'

        orocrm_task_my_tasks:
            label: 'orocrm.task.menu.my_tasks'
            route: 'orocrm_task_my_tasks'
            extras:
                position: 15

    tree:
        application_menu:
            children:
                activities_tab:
                    children:
                        task_list: ~
        usermenu:
            children:
                orocrm_task_my_tasks: ~

oro_titles:
    orocrm_task_index: ~
    orocrm_task_view: '%%entity.subject%%'
    orocrm_task_create: oro.ui.create_entity
    orocrm_task_update: '%%entity.subject%% - Edit'
    orocrm_task_my_tasks: "My Tasks - %%username%%"
