placeholders:
    oro_reminder_reminder_templates:
        items:
            task_reminder_template: ~

    view_content_data_additional_information:
        items:
            orocrm_user_tasks: ~

    view_navButtons_before:
        items:
            orocrm_my_tasks_button: ~

items:
    task_reminder_template:
        template: OroCRMTaskBundle:Task:reminderTemplate.html.twig

    orocrm_user_tasks:
        template: OroCRMTaskBundle:Task:userTasks.html.twig
        applicable: "@oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)"
        acl: orocrm_task_view

    orocrm_assign_task_button:
        template: OroCRMTaskBundle:Task:assignTaskButton.html.twig
        applicable: "@oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)"
        acl: orocrm_task_create

    orocrm_assign_task_link:
        template: OroCRMTaskBundle:Task:assignTaskLink.html.twig
        applicable: "@oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)"
        acl: orocrm_task_create

    orocrm_add_task_button:
        template: OroCRMTaskBundle:Task:activityButton.html.twig
        acl: orocrm_task_create

    orocrm_add_task_link:
        template: OroCRMTaskBundle:Task:activityLink.html.twig
        acl: orocrm_task_create

    orocrm_my_tasks_button:
        template: OroCRMTaskBundle:Task:myTasksButton.html.twig
        applicable: "@orocrm_task.placeholder.filter->isCalendarTasksVisible($entity$)"
        acl: orocrm_task_view
