datagrid:
    orocrm-marketing-list-grid:
        extended_entity_name: OroCRM\Bundle\MarketingListBundle\Entity\MarketingList
        source:
            type: orm
            query:
                select:
                    - ml.id
                    - ml.name
                    - ml.entity
                    - type.label as listType
                    - ml.createdAt
                    - ml.lastRun
                    - segment.lastRun as segmentLastRun
                from:
                    - { table: OroCRM\Bundle\MarketingListBundle\Entity\MarketingList, alias: ml }
                join:
                    inner:
                        - { join: ml.type, alias: type }
                    left:
                        - { join: ml.segment, alias: segment }
        columns:
            name:
                label:          orocrm.marketinglist.name.label
            entity:
                label:          orocrm.marketinglist.entity.label
                type:           twig
                template:       OroEntityBundle:Datagrid:Property/entity.html.twig
                frontend_type:  html
                context:
                    entity_provider: '@orocrm_marketing_list.entity_provider'
            listType:
                label:          orocrm.marketinglist.type.label
                type:           twig
                choices:        '@orocrm_marketing_list.datagrid.marketing_list_type.provider->getListTypeChoices'
                frontend_type:  html
                template:       OroCRMMarketingListBundle:MarketingList:Datagrid/Property/listType.html.twig
            createdAt:
                label:          orocrm.marketinglist.created_at.label
                frontend_type:  datetime
            lastRun:
                label:          orocrm.marketinglist.last_run.label
                frontend_type:  datetime
        filters:
            columns:
                name:
                    type:        string
                    data_name:   ml.name
                entity:
                    type:      choice
                    data_name: ml.entity
                    options:
                        field_options:
                            multiple:          true
                            choices:           '@oro_entity.datagrid_helper->getEntityNames'
                            translatable_options: false
                listType:
                    type:               choice
                    data_name:          ml.type
                    options:
                        field_options:
                            choices:    '@orocrm_marketing_list.datagrid.marketing_list_type.provider->getListTypeChoices'
                createdAt:
                    type:       datetime
                    data_name:  ml.createdAt
                lastRun:
                    type:       datetime
                    data_name:  ml.lastRun
        sorters:
            columns:
                name:        { data_name: ml.name }
                createdAt:   { data_name: ml.createdAt }
                lastRun:     { data_name: ml.lastRun }
        properties:
            id: ~
            view_link:
                type: url
                route: orocrm_marketing_list_view
                params: [ id ]
            update_link:
                type: url
                route: orocrm_marketing_list_update
                params:
                    - id
            delete_link:
                type: url
                route: orocrm_api_delete_marketinglist
                params:
                    - id
        actions:
            view:
                type:         navigate
                label:        oro.grid.action.view
                link:         view_link
                icon:         eye-open
                acl_resource: orocrm_marketing_list_view
                rowAction:    true
            update:
                type:          navigate
                acl_resource:  orocrm_marketing_list_update
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
                launcherOptions:
                    className: 'no-hash mobile-hide'
            delete:
                type:          delete
                acl_resource:  orocrm_marketing_list_delete
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link
                launcherOptions:
                    className: 'no-hash mobile-hide'
        options:
            entity_pagination: true

    # Segment based grids mixins:
    orocrm-marketing-full-mixin:
        source:
            query:
                join:
                    left:
                        -
                            join: 'OroCRM\Bundle\MarketingListBundle\Entity\MarketingListItem'
                            alias: 'mli'
                            conditionType: 'WITH'
                            condition: 'mli.entityId = __root_entity__.id AND mli.marketingList = :marketingListEntity'
        options:
            export: false
            skip_count_walker: true
            mixin: true

    orocrm-marketing-list-items-base-mixin:
        source:
            query:
                select:
                    - __root_entity__.id
                    - mli.contactedTimes
                    - mli.lastContactedAt
                join:
                    left:
                        -
                            join: 'OroCRM\Bundle\MarketingListBundle\Entity\MarketingListRemovedItem'
                            alias: 'mlr'
                            conditionType: 'WITH'
                            condition: 'mlr.entityId = __root_entity__.id AND mlr.marketingList = :marketingListEntity'
                        -
                            join: 'OroCRM\Bundle\MarketingListBundle\Entity\MarketingListItem'
                            alias: 'mli'
                            conditionType: 'WITH'
                            condition: 'mli.entityId = __root_entity__.id AND mli.marketingList = :marketingListEntity'
        columns:
            contactedTimes:
                label: orocrm.marketinglist.datagrid.contactedTimes
            lastContactedAt:
                label: orocrm.marketinglist.datagrid.lastContactedAt
                frontend_type: datetime
        filters:
            columns:
                contactedTimes:  { type: number-range,   data_name: mli.contactedTimes }
                lastContactedAt: { type: datetime, data_name: mli.lastContactedAt }
        sorters:
            columns:
                contactedTimes:  { data_name: mli.contactedTimes }
                lastContactedAt: { data_name: mli.lastContactedAt }
        properties:
            marketingList: ~
        action_configuration: ['@orocrm_marketing_list.datagrid.action_permission_provider', "getMarketingListItemPermissions"]
        options:
            skip_count_walker: true
            mixin: true

    orocrm-marketing-list-items-base-unsubscribe-mixin:
        extends: orocrm-marketing-list-items-base-mixin
        source:
            query:
                select:
                    - (CASE WHEN mlu.id IS NULL THEN true ELSE false END) as subscribed
                join:
                    left:
                        -
                            join: 'OroCRM\Bundle\MarketingListBundle\Entity\MarketingListUnsubscribedItem'
                            alias: 'mlu'
                            conditionType: 'WITH'
                            condition: 'mlu.entityId = __root_entity__.id AND mlu.marketingList = :marketingListEntity'
        columns:
            subscribed:
                label: orocrm.marketinglist.datagrid.subscribed
                frontend_type: boolean
        filters:
            columns:
                subscribed: { type: boolean, data_name: subscribed }
        sorters:
            columns:
                subscribed: { data_name: subscribed }
        properties:
            subscribe_link:
                type: url
                route: orocrm_api_subscribe_marketinglist_unsubscribeditem
                params: [ marketingList, id ]
            unsubscribe_link:
                type: url
                route: orocrm_api_unsubscribe_marketinglist_unsubscribeditem
                params: [ marketingList, id ]
        actions:
            subscribe:
                type:         ajax
                label:        orocrm.marketinglist.action.subscribe
                link:         subscribe_link
                icon:         plus
                acl_resource: orocrm_marketinglist_unsubscribed_item_delete
            unsubscribe:
                type:         ajax
                label:        orocrm.marketinglist.action.unsubscribe
                link:         unsubscribe_link
                icon:         minus
                acl_resource: orocrm_marketinglist_unsubscribed_item_create

    orocrm-marketing-list-items-mixin:
        extends: orocrm-marketing-list-items-base-unsubscribe-mixin
        source:
            query:
                where:
                    and:
                        - mlr.id IS NULL
        properties:
            remove_link:
                type: url
                route: orocrm_api_remove_marketinglist_removeditem
                params: [ marketingList, id ]
        actions:
            remove:
                type:         ajaxdelete
                label:        orocrm.marketinglist.action.remove
                link:         remove_link
                icon:         remove
                acl_resource: orocrm_marketing_list_removed_item_create
                defaultMessages:
                    confirm_title:   orocrm.marketinglist.remove_dialog.confirm_title
                    confirm_ok:      orocrm.marketinglist.remove_dialog.confirm_ok
                    confirm_cancel:  orocrm.marketinglist.remove_dialog.confirm_cancel
                    confirm_content: orocrm.marketinglist.remove_dialog.content
                    success:         orocrm.marketinglist.remove_dialog.success

    orocrm-marketing-list-removed-items-mixin:
        extends: orocrm-marketing-list-items-base-mixin
        source:
            query:
                where:
                    and:
                        - mlr.id IS NOT NULL
        properties:
            unremove_link:
                type: url
                route: orocrm_api_unremove_marketinglist_removeditem
                params: [ marketingList, id ]
        actions:
            unremove:
                type:         ajaxdelete
                label:        orocrm.marketinglist.action.unremove
                link:         unremove_link
                icon:         undo
                acl_resource: orocrm_marketing_list_removed_item_delete
                defaultMessages:
                    confirm_title:   orocrm.marketinglist.unremove_dialog.confirm_title
                    confirm_ok:      orocrm.marketinglist.unremove_dialog.confirm_ok
                    confirm_cancel:  orocrm.marketinglist.unremove_dialog.confirm_cancel
                    confirm_content: orocrm.marketinglist.unremove_dialog.content
                    success:         orocrm.marketinglist.unremove_dialog.success

    orocrm-marketing-list-entities-base-unsubscribe-mixin:
        source:
            query:
                join:
                    left:
                        -
                            join: 'OroCRM\Bundle\MarketingListBundle\Entity\MarketingListUnsubscribedItem'
                            alias: 'mlu'
                            conditionType: 'WITH'
                            condition: 'mlu.entityId = __root_entity__.id AND mlu.marketingList = :marketingListEntity'
                        -
                            join: 'OroCRM\Bundle\MarketingListBundle\Entity\MarketingListRemovedItem'
                            alias: 'mlr'
                            conditionType: 'WITH'
                            condition: 'mlr.entityId = __root_entity__.id AND mlr.marketingList = :marketingListEntity'
                where:
                    and:
                        - mlr.id IS NULL
                        - mlu.id IS NULL

    orocrm-marketing-list-entities-mixin:
        extends: orocrm-marketing-list-entities-base-unsubscribe-mixin
        source:
            query:
                join:
                    left:
                        -
                            join: 'OroCRM\Bundle\MarketingListBundle\Entity\MarketingListItem'
                            alias: 'mli'
                            conditionType: 'WITH'
                            condition: 'mli.entityId = __root_entity__.id AND mli.marketingList = :marketingListEntity'
        options:
            export: false
            skip_count_walker: true
            mixin: true

    # Manual marketing list based mixins
    orocrm-marketing-list-manual-items-base-mixin:
        source:
            query:
                select:
                    - __root_entity__.id
                    - mli.contactedTimes
                    - mli.lastContactedAt
                join:
                    inner:
                        -
                            join: 'OroCRM\Bundle\MarketingListBundle\Entity\MarketingListItem'
                            alias: 'mli'
                            conditionType: 'WITH'
                            condition: 'mli.entityId = __root_entity__.id AND mli.marketingList = :marketingListEntity'
                    left:
                        -
                            join: 'OroCRM\Bundle\MarketingListBundle\Entity\MarketingListRemovedItem'
                            alias: 'mlr'
                            conditionType: 'WITH'
                            condition: 'mlr.entityId = __root_entity__.id AND mlr.marketingList = :marketingListEntity'
        columns:
            contactedTimes:
                label: orocrm.marketinglist.datagrid.contactedTimes
            lastContactedAt:
                label: orocrm.marketinglist.datagrid.lastContactedAt
                frontend_type: datetime
        filters:
            columns:
                contactedTimes:  { type: number-range,   data_name: mli.contactedTimes }
                lastContactedAt: { type: datetime, data_name: mli.lastContactedAt }
        sorters:
            columns:
                contactedTimes:  { data_name: mli.contactedTimes }
                lastContactedAt: { data_name: mli.lastContactedAt }
        properties:
            marketingList: ~
        action_configuration: ['@orocrm_marketing_list.datagrid.action_permission_provider', "getMarketingListItemPermissions"]
        options:
            skip_count_walker: true
            mixin: true

    orocrm-marketing-list-manual-items-base-unsubscribe-mixin:
        extends: orocrm-marketing-list-manual-items-base-mixin
        source:
            query:
                select:
                    - (CASE WHEN mlu.id IS NULL THEN true ELSE false END) as subscribed
                join:
                    left:
                        -
                            join: 'OroCRM\Bundle\MarketingListBundle\Entity\MarketingListUnsubscribedItem'
                            alias: 'mlu'
                            conditionType: 'WITH'
                            condition: 'mlu.entityId = __root_entity__.id AND mlu.marketingList = :marketingListEntity'
        columns:
            subscribed:
                label: orocrm.marketinglist.datagrid.subscribed
                frontend_type: boolean
        filters:
            columns:
                subscribed: { type: boolean, data_name: subscribed }
        sorters:
            columns:
                subscribed: { data_name: subscribed }
        properties:
            subscribe_link:
                type: url
                route: orocrm_api_subscribe_marketinglist_unsubscribeditem
                params: [ marketingList, id ]
            unsubscribe_link:
                type: url
                route: orocrm_api_unsubscribe_marketinglist_unsubscribeditem
                params: [ marketingList, id ]
        actions:
            subscribe:
                type:         ajax
                label:        orocrm.marketinglist.action.subscribe
                link:         subscribe_link
                icon:         plus
                acl_resource: orocrm_marketinglist_unsubscribed_item_delete
            unsubscribe:
                type:         ajax
                label:        orocrm.marketinglist.action.unsubscribe
                link:         unsubscribe_link
                icon:         minus
                acl_resource: orocrm_marketinglist_unsubscribed_item_create

    orocrm-marketing-list-manual-items-mixin:
        extends: orocrm-marketing-list-manual-items-base-unsubscribe-mixin
        source:
            query:
                where:
                    and:
                        - mlr.id IS NULL
        properties:
            remove_link:
                type: url
                route: orocrm_api_remove_marketinglist_removeditem
                params: [ marketingList, id ]
        actions:
            remove:
                type:         ajaxdelete
                label:        orocrm.marketinglist.action.remove
                link:         remove_link
                icon:         remove
                acl_resource: orocrm_marketing_list_removed_item_create
                defaultMessages:
                    confirm_title:   orocrm.marketinglist.remove_dialog.confirm_title
                    confirm_ok:      orocrm.marketinglist.remove_dialog.confirm_ok
                    confirm_cancel:  orocrm.marketinglist.remove_dialog.confirm_cancel
                    confirm_content: orocrm.marketinglist.remove_dialog.content
                    success:         orocrm.marketinglist.remove_dialog.success

    orocrm-marketing-list-manual-removed-items-mixin:
        extends: orocrm-marketing-list-manual-items-base-mixin
        source:
            query:
                where:
                    and:
                        - mlr.id IS NOT NULL
        properties:
            unremove_link:
                type: url
                route: orocrm_api_unremove_marketinglist_removeditem
                params: [ marketingList, id ]
        actions:
            unremove:
                type:         ajaxdelete
                label:        orocrm.marketinglist.action.unremove
                link:         unremove_link
                icon:         undo
                acl_resource: orocrm_marketing_list_removed_item_delete
                defaultMessages:
                    confirm_title:   orocrm.marketinglist.unremove_dialog.confirm_title
                    confirm_ok:      orocrm.marketinglist.unremove_dialog.confirm_ok
                    confirm_cancel:  orocrm.marketinglist.unremove_dialog.confirm_cancel
                    confirm_content: orocrm.marketinglist.unremove_dialog.content
                    success:         orocrm.marketinglist.unremove_dialog.success

    orocrm-marketing-list-manual-entities-mixin:
        extends: orocrm-marketing-list-entities-base-unsubscribe-mixin
        source:
            query:
                join:
                    inner:
                        -
                            join: 'OroCRM\Bundle\MarketingListBundle\Entity\MarketingListItem'
                            alias: 'mli'
                            conditionType: 'WITH'
                            condition: 'mli.entityId = __root_entity__.id AND mli.marketingList = :marketingListEntity'
        options:
            export: false
            skip_count_walker: true
            mixin: true
