parameters:
    orocrm_marketing_list.form.type.marketing_list.class: OroCRM\Bundle\MarketingListBundle\Form\Type\MarketingListType
    orocrm_marketing_list.form.type.marketing_list_removed_item.class: OroCRM\Bundle\MarketingListBundle\Form\Type\MarketingListTypeRemovedItemType
    orocrm_marketing_list.form.type.marketing_list_unsubscribed_item.class: OroCRM\Bundle\MarketingListBundle\Form\Type\MarketingListTypeUnsubscribedItemType
    orocrm_marketing_list.form.handler.marketing_list.class: OroCRM\Bundle\MarketingListBundle\Form\Handler\MarketingListHandler
    orocrm_marketing_list.form.type.entity_choice.class: OroCRM\Bundle\MarketingListBundle\Form\Type\ContactInformationEntityChoiceType
    orocrm_marketing_list.form.type.marketing_list_select.class: OroCRM\Bundle\MarketingListBundle\Form\Type\MarketingListSelectType

services:
    # MarketingList
    orocrm_marketing_list.form.type.marketing_list:
        class: %orocrm_marketing_list.form.type.marketing_list.class%
        tags:
            - { name: form.type, alias: orocrm_marketing_list }

    orocrm_marketing_list.form.marketing_list:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - "orocrm_marketing_list_form"
            - "orocrm_marketing_list"

    orocrm_marketing_list.form.type.marketing_list_removed_item:
        class: %orocrm_marketing_list.form.type.marketing_list_removed_item.class%
        tags:
            - { name: form.type, alias: orocrm_marketing_list_removed_item }

    orocrm_marketing_list.form.type.marketing_list_removed_item_api:
        parent: oro_form.type.api
        arguments:
            - 'orocrm_marketing_list_removed_item_api'
            - "@orocrm_marketing_list.form.type.marketing_list_removed_item"
        tags:
            - { name: form.type, alias: orocrm_marketing_list_removed_item_api }

    orocrm_marketing_list.form.marketing_list_removed_item:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - ~
            - 'orocrm_marketing_list_removed_item_api'

    orocrm_marketing_list.form.handler.marketing_list_removed_item:
        parent: oro_form.form_handler.api
        scope: request
        calls:
            - [setForm, ['@orocrm_marketing_list.form.marketing_list_removed_item']]

    orocrm_marketing_list.form.type.marketing_list_unsubscribed_item:
        class: %orocrm_marketing_list.form.type.marketing_list_unsubscribed_item.class%
        tags:
            - { name: form.type, alias: orocrm_marketing_list_unsubscribed_item }

    orocrm_marketing_list.form.type.marketing_list_unsubscribed_item_api:
        parent: oro_form.type.api
        arguments:
            - 'orocrm_marketing_list_unsubscribed_item_api'
            - "@orocrm_marketing_list.form.type.marketing_list_unsubscribed_item"
        tags:
            - { name: form.type, alias: orocrm_marketing_list_unsubscribed_item_api }

    orocrm_marketing_list.form.marketing_list_unsubscribed_item:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - ~
            - 'orocrm_marketing_list_unsubscribed_item_api'

    orocrm_marketing_list.form.handler.marketing_list_unsubscribed_item:
        parent: oro_form.form_handler.api
        scope: request
        calls:
            - [setForm,  ["@orocrm_marketing_list.form.marketing_list_unsubscribed_item"]]

    orocrm_marketing_list.form.handler.marketing_list:
        class: %orocrm_marketing_list.form.handler.marketing_list.class%
        scope: request
        arguments:
            - "@orocrm_marketing_list.form.marketing_list"
            - "@request"
            - "@doctrine"
            - "@validator"
            - "@translator"

    orocrm_marketing_list.form.type.entity_choice:
        class: %orocrm_marketing_list.form.type.entity_choice.class%
        arguments:
            - "@orocrm_marketing_list.entity_provider.contact_information"
        tags:
            - { name: form.type, alias: orocrm_marketing_list_contact_information_entity_choice }

    orocrm_marketing_list.form.type.marketing_list_select:
        class: %orocrm_marketing_list.form.type.marketing_list_select.class%
        tags:
            - { name: form.type, alias: "orocrm_marketing_list_select" }
