workflows:
    b2b_flow_lead:
        transitions:
            qualify:
                step_to: qualified
                is_start: true
                is_unavailable_hidden: true
                acl_resource: oro_sales_opportunity_create
                frontend_options:
                    icon: 'fa-check'
                    class: 'btn-primary'
                form_options:
                    attribute_fields:
                        opportunity_name:
                            form_type: Symfony\Component\Form\Extension\Core\Type\TextType
                            options:
                                required: true
                                constraints:
                                  - NotBlank: ~
                        customer_association:
                            form_type: Oro\Bundle\SalesBundle\Form\Type\CustomerType
                            options:
                                required: false
                                parent_class: Oro\Bundle\AccountBundle\Entity\Account
                        company_name:
                            form_type: Symfony\Component\Form\Extension\Core\Type\TextType
                            options:
                                required: false
                        notes:
                            form_type: Oro\Bundle\FormBundle\Form\Type\OroResizeableRichTextType
                            options:
                                required: false
                    attribute_default_values:
                        opportunity_name: $lead.name
                        customer_association: $lead.customer_association
                        company_name: $lead.companyName
                        notes: $lead.notes
                    form_init:
                        - '@find_entity': # try to find account by company name
                            conditions:
                                '@and': # if customer is empty and company name is specified
                                    - '@empty':     $customer_association
                                    - '@not_empty': $company_name
                            parameters:
                                class: Oro\Bundle\AccountBundle\Entity\Account
                                attribute: $account
                                where:
                                    name: $company_name
                            case_insensitive: true
                        - '@find_entity': # try to find customer by company name
                            conditions:
                                '@and': # if customer is empty and company name is specified
                                    - '@empty':     $customer_association
                                    - '@not_empty': $account
                            parameters:
                                class:     Oro\Bundle\SalesBundle\Entity\Customer
                                attribute: $customer_association
                                where:
                                    account: $account
                transition_definition: qualify_definition
            cancel:
                step_to: cancelled
                is_start: true
                is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-close'
                transition_definition: cancel_definition
            reactivate:
                step_to: new
                is_start: true
                is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-repeat'
                transition_definition: reactivate_definition
