placeholders:
    placeholders:
        view_content_data_additional_information:
            items:
                oro_user_cases_grid: ~
                oro_account_cases_grid: ~
                oro_contact_cases_grid: ~

    items:
        oro_user_cases_grid:
            template: '@@OroCase/Case/userCases.html.twig'
            applicable: '@oro_ui.placeholder.filter->isInstanceOf($entity$, Oro\Bundle\UserBundle\Entity\User)'
        oro_account_cases_grid:
            template: '@@OroCase/Case/accountCases.html.twig'
            applicable: '@oro_ui.placeholder.filter->isInstanceOf($entity$, Oro\Bundle\AccountBundle\Entity\Account)'
        oro_contact_cases_grid:
            template: '@@OroCase/Case/contactCases.html.twig'
            applicable: '@oro_ui.placeholder.filter->isInstanceOf($entity$, Oro\Bundle\ContactBundle\Entity\Contact)'
