workflows:
    b2b_flow_sales_funnel:
        attributes:
            sales_funnel_start_date:
                property_path: sales_funnel.startDate
            sales_funnel_owner:
                property_path: sales_funnel.owner
            lead:
                property_path: sales_funnel.lead
            lead_notes:
                property_path: sales_funnel.lead.notes
            new_notes:
                type: string
            new_opportunity_name:
                type: string
            new_customer_association:
                type:  entity
                options:
                    class: Oro\Bundle\SalesBundle\Entity\Customer
                property_path: sales_funnel.opportunity.customerAssociation
            new_account:
                type: entity
                options:
                    class: Oro\Bundle\AccountBundle\Entity\Account
            new_company_name:
                type: string
            opportunity:
                property_path: sales_funnel.opportunity
            opportunity_name:
                property_path: sales_funnel.opportunity.name
            opportunity_notes:
                property_path: sales_funnel.opportunity.notes
            contact:
                property_path: sales_funnel.opportunity.contact
            probability:
                property_path: sales_funnel.opportunity.probability
            budget_amount:
                property_path: sales_funnel.opportunity.budgetAmount
                type: entity
                options:
                    class: Oro\Bundle\CurrencyBundle\Entity\MultiCurrency
            customer_need:
                property_path: sales_funnel.opportunity.customerNeed
            proposed_solution:
                property_path: sales_funnel.opportunity.proposedSolution
            close_reason_name: # temporary attribute to find close reason by its name
                type: string
            close_reason:
                property_path: sales_funnel.opportunity.closeReason
            close_revenue:
                property_path: sales_funnel.opportunity.closeRevenue
                type: entity
                options:
                    class: Oro\Bundle\CurrencyBundle\Entity\MultiCurrency
            close_date:
                property_path: sales_funnel.opportunity.closeDate
