workflows:
    b2b_flow_sales_funnel:
        transitions:
            start_from_lead:
                step_to: new_lead
                is_start: true
                is_unavailable_hidden: true
                acl_resource: oro_sales_salesfunnel_create
                display_type: page
                frontend_options:
                    icon: 'fa-phone'
                    class: 'btn-success'
                    page:
                        parent_route: 'oro_sales_salesfunnel_index'
                        parent_label: oro.sales.salesfunnel.entity_plural_label
                        title: oro.sales.salesfunnel.new_entity
                form_options:
                    attribute_fields:
                        sales_funnel_owner:
                            form_type: Oro\Bundle\UserBundle\Form\Type\OrganizationUserAclSelectType
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                        sales_funnel_start_date:
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                        lead:
                            form_type: Oro\Bundle\SalesBundle\Form\Type\LeadSelectType
                            options:
                                grid_name: 'sales-funnel-lead-grid'
                                configs:
                                    component: 'grid'
                                    grid:
                                        name: 'sales-funnel-lead-grid'
                                required: true
                                constraints:
                                    - NotBlank:
                                        message: 'Lead must be set'
                    form_init:
                        - '@create_date':
                            attribute: $sales_funnel_start_date
                        - '@assign_active_user':
                            attribute: $sales_funnel_owner
                transition_definition: start_from_lead
            start_from_opportunity:
                step_to: new_opportunity
                is_start: true
                is_unavailable_hidden: true
                acl_resource: oro_sales_salesfunnel_create
                display_type: page
                frontend_options:
                    icon: 'fa-usd'
                    class: 'btn-success'
                    page:
                        parent_route: 'oro_sales_salesfunnel_index'
                        parent_label: oro.sales.salesfunnel.entity_plural_label
                        title: oro.sales.salesfunnel.new_entity
                form_options:
                    attribute_fields:
                        sales_funnel_owner:
                            form_type: Oro\Bundle\UserBundle\Form\Type\OrganizationUserAclSelectType
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                        sales_funnel_start_date:
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                        opportunity:
                            form_type: Oro\Bundle\SalesBundle\Form\Type\OpportunitySelectType
                            options:
                                grid_name: 'sales-funnel-opportunity-grid'
                                configs:
                                    component: 'grid'
                                    grid:
                                        name: 'sales-funnel-opportunity-grid'
                                required: true
                                constraints:
                                    - NotBlank:
                                        message: 'Opportunity must be set'
                    form_init:
                        - '@create_date':
                            attribute: $sales_funnel_start_date
                        - '@assign_active_user':
                            attribute: $sales_funnel_owner
                transition_definition: start_from_opportunity
            disqualify:
                step_to: disqualified_lead
                is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-close'
                transition_definition: disqualify_definition
            follow_up:
                step_to: disqualified_lead
                is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-comment'
                form_options:
                    attribute_fields:
                        lead_notes: ~
                transition_definition: follow_up_definition
            reactivate:
                step_to: new_lead
                is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-repeat'
                transition_definition: reactivate_definition
            qualify:
                step_to: new_opportunity
                is_unavailable_hidden: true
                acl_resource: oro_sales_opportunity_create
                frontend_options:
                    icon: 'fa-check'
                    class: 'btn-primary'
                form_options:
                    attribute_fields:
                        new_opportunity_name:
                            options:
                                required: true
                                constraints:
                                  - NotBlank: ~
                        new_customer_association:
                            form_type: Oro\Bundle\SalesBundle\Form\Type\CustomerType
                            options:
                                required: false
                                parent_class: Oro\Bundle\AccountBundle\Entity\Account
                                label: 'Test'
                        new_company_name: ~
                        new_notes:
                            form_type: Oro\Bundle\FormBundle\Form\Type\OroResizeableRichTextType
                    attribute_default_values:
                        new_opportunity_name: $lead.name
                        new_customer_association: $lead.customerAssociation
                        new_company_name: $lead.companyName
                        new_notes: $lead.notes
                    form_init:
                        - '@find_entity': # try to find account by company name
                            conditions:
                                '@and': # if customer association is empty and company name is specified
                                    - '@empty':     $new_customer_association
                                    - '@not_empty': $new_company_name
                            parameters:
                                class: Oro\Bundle\AccountBundle\Entity\Account
                                attribute: $new_account
                                where:
                                    name: $new_company_name
                            case_insensitive: true
                        - '@find_entity': # try to find customer by company name
                            conditions:
                                '@and': # if customer is empty and company name is specified
                                    - '@empty':     $new_customer_association
                                    - '@not_empty': $new_account
                            parameters:
                                class:     Oro\Bundle\SalesBundle\Entity\Customer
                                attribute: $new_customer_association
                                where:
                                    account: $new_account
                transition_definition: qualify_definition
            develop:
                step_to: developed_opportunity
                is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-play'
                    class: 'btn-primary'
                transition_definition: develop_definition
                form_options:
                    attribute_fields:
                        contact: ~
                        new_customer_association:
                            form_type: Oro\Bundle\SalesBundle\Form\Type\CustomerType
                            options:
                                required: false
                                parent_class: Oro\Bundle\AccountBundle\Entity\Account
                        budget_amount:
                            form_type: Oro\Bundle\CurrencyBundle\Form\Type\MultiCurrencyType
                        probability: ~
                        customer_need: ~
                        proposed_solution: ~
            close_as_won:
                step_to: won_opportunity
                is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-check-circle-o'
                    class: 'btn-success'
                transition_definition: close_as_won_definition
                form_options:
                    attribute_fields:
                        close_revenue:
                            form_type: Oro\Bundle\CurrencyBundle\Form\Type\MultiCurrencyType
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                        close_date:
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                    form_init:
                        - '@create_date':
                            conditions:
                                '@empty': $close_date
                            parameters:
                                attribute: $close_date
            close_as_lost:
                step_to: lost_opportunity
                is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-times'
                    class: 'btn-danger'
                transition_definition: close_as_lost_definition
                form_options:
                    attribute_fields:
                        close_reason_name:
                            form_type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
                            options:
                                required: true
                                placeholder: false
                                choices:
                                    Outsold: outsold
                                    Cancelled: cancelled
                                constraints:
                                    - NotBlank: ~
                        close_date:
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                    form_init:
                        - '@assign_value':
                            conditions:
                                '@not_empty': $close_reason
                            parameters: [$close_reason_name, $close_reason.name]
                        - '@create_date':
                            conditions:
                                '@empty': $close_date
                            parameters:
                                attribute: $close_date
            reopen:
                step_to: new_opportunity
                is_unavailable_hidden: true
                frontend_options:
                    icon: 'fa-backward'
                    class: 'btn-primary'
                transition_definition: reopen_definition
